
# This file is automatically generated, you probably don't want to edit this

jamovidescribeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovidescribeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            outcome_variable = NULL, ...) {

            super$initialize(
                package="esci4",
                name="jamovidescribe",
                requiresData=TRUE,
                ...)

            private$..outcome_variable <- jmvcore::OptionVariable$new(
                "outcome_variable",
                outcome_variable,
                permitted=list(
                    "numeric"))

            self$.addOption(private$..outcome_variable)
        }),
    active = list(
        outcome_variable = function() private$..outcome_variable$value),
    private = list(
        ..outcome_variable = NA)
)

jamovidescribeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovidescribeResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Describe")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Describe"))}))

jamovidescribeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovidescribeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "esci4",
                name = "jamovidescribe",
                version = c(1,0,0),
                options = options,
                results = jamovidescribeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Describe
#'
#' 
#' @param data .
#' @param outcome_variable .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
jamovidescribe <- function(
    data,
    outcome_variable) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jamovidescribe requires jmvcore to be installed (restart may be required)")

    if ( ! missing(outcome_variable)) outcome_variable <- jmvcore::resolveQuo(jmvcore::enquo(outcome_variable))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(outcome_variable), outcome_variable, NULL))


    options <- jamovidescribeOptions$new(
        outcome_variable = outcome_variable)

    analysis <- jamovidescribeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

