
# This file is automatically generated, you probably don't want to edit this

jamovimdifftwoOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovimdifftwoOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            switch = "from_raw",
            outcome_variable = NULL,
            grouping_variable = NULL,
            comparison_mean = NULL,
            comparison_sd = NULL,
            comparison_n = NULL,
            reference_mean = NULL,
            reference_sd = NULL,
            reference_n = NULL,
            comparison_level_name = "Comparison level",
            reference_level_name = "Reference level",
            outcome_variable_name = "Outcome variable",
            conf_level = 95,
            assume_equal_variance = TRUE, ...) {

            super$initialize(
                package="esci4",
                name="jamovimdifftwo",
                requiresData=TRUE,
                ...)

            private$..switch <- jmvcore::OptionList$new(
                "switch",
                switch,
                default="from_raw",
                options=list(
                    "from_raw",
                    "from_summary"))
            private$..outcome_variable <- jmvcore::OptionVariable$new(
                "outcome_variable",
                outcome_variable,
                permitted=list(
                    "numeric"))
            private$..grouping_variable <- jmvcore::OptionVariable$new(
                "grouping_variable",
                grouping_variable,
                permitted=list(
                    "factor"))
            private$..comparison_mean <- jmvcore::OptionNumber$new(
                "comparison_mean",
                comparison_mean)
            private$..comparison_sd <- jmvcore::OptionNumber$new(
                "comparison_sd",
                comparison_sd)
            private$..comparison_n <- jmvcore::OptionInteger$new(
                "comparison_n",
                comparison_n,
                min=1)
            private$..reference_mean <- jmvcore::OptionNumber$new(
                "reference_mean",
                reference_mean)
            private$..reference_sd <- jmvcore::OptionNumber$new(
                "reference_sd",
                reference_sd)
            private$..reference_n <- jmvcore::OptionInteger$new(
                "reference_n",
                reference_n,
                min=1)
            private$..comparison_level_name <- jmvcore::OptionString$new(
                "comparison_level_name",
                comparison_level_name,
                default="Comparison level")
            private$..reference_level_name <- jmvcore::OptionString$new(
                "reference_level_name",
                reference_level_name,
                default="Reference level")
            private$..outcome_variable_name <- jmvcore::OptionString$new(
                "outcome_variable_name",
                outcome_variable_name,
                default="Outcome variable")
            private$..conf_level <- jmvcore::OptionNumber$new(
                "conf_level",
                conf_level,
                min=1,
                max=99.999999,
                default=95)
            private$..assume_equal_variance <- jmvcore::OptionBool$new(
                "assume_equal_variance",
                assume_equal_variance,
                default=TRUE)

            self$.addOption(private$..switch)
            self$.addOption(private$..outcome_variable)
            self$.addOption(private$..grouping_variable)
            self$.addOption(private$..comparison_mean)
            self$.addOption(private$..comparison_sd)
            self$.addOption(private$..comparison_n)
            self$.addOption(private$..reference_mean)
            self$.addOption(private$..reference_sd)
            self$.addOption(private$..reference_n)
            self$.addOption(private$..comparison_level_name)
            self$.addOption(private$..reference_level_name)
            self$.addOption(private$..outcome_variable_name)
            self$.addOption(private$..conf_level)
            self$.addOption(private$..assume_equal_variance)
        }),
    active = list(
        switch = function() private$..switch$value,
        outcome_variable = function() private$..outcome_variable$value,
        grouping_variable = function() private$..grouping_variable$value,
        comparison_mean = function() private$..comparison_mean$value,
        comparison_sd = function() private$..comparison_sd$value,
        comparison_n = function() private$..comparison_n$value,
        reference_mean = function() private$..reference_mean$value,
        reference_sd = function() private$..reference_sd$value,
        reference_n = function() private$..reference_n$value,
        comparison_level_name = function() private$..comparison_level_name$value,
        reference_level_name = function() private$..reference_level_name$value,
        outcome_variable_name = function() private$..outcome_variable_name$value,
        conf_level = function() private$..conf_level$value,
        assume_equal_variance = function() private$..assume_equal_variance$value),
    private = list(
        ..switch = NA,
        ..outcome_variable = NA,
        ..grouping_variable = NA,
        ..comparison_mean = NA,
        ..comparison_sd = NA,
        ..comparison_n = NA,
        ..reference_mean = NA,
        ..reference_sd = NA,
        ..reference_n = NA,
        ..comparison_level_name = NA,
        ..reference_level_name = NA,
        ..outcome_variable_name = NA,
        ..conf_level = NA,
        ..assume_equal_variance = NA)
)

jamovimdifftwoResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovimdifftwoResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Mdiff - Two Groups")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Mdiff - Two Groups"))}))

jamovimdifftwoBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovimdifftwoBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "esci4",
                name = "jamovimdifftwo",
                version = c(1,0,0),
                options = options,
                results = jamovimdifftwoResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Mdiff - Two Groups
#'
#' 
#' @param switch .
#' @param data .
#' @param outcome_variable .
#' @param grouping_variable .
#' @param comparison_mean .
#' @param comparison_sd .
#' @param comparison_n .
#' @param reference_mean .
#' @param reference_sd .
#' @param reference_n .
#' @param comparison_level_name .
#' @param reference_level_name .
#' @param outcome_variable_name .
#' @param conf_level .
#' @param assume_equal_variance .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
jamovimdifftwo <- function(
    switch = "from_raw",
    data,
    outcome_variable,
    grouping_variable,
    comparison_mean,
    comparison_sd,
    comparison_n,
    reference_mean,
    reference_sd,
    reference_n,
    comparison_level_name = "Comparison level",
    reference_level_name = "Reference level",
    outcome_variable_name = "Outcome variable",
    conf_level = 95,
    assume_equal_variance = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jamovimdifftwo requires jmvcore to be installed (restart may be required)")

    if ( ! missing(outcome_variable)) outcome_variable <- jmvcore::resolveQuo(jmvcore::enquo(outcome_variable))
    if ( ! missing(grouping_variable)) grouping_variable <- jmvcore::resolveQuo(jmvcore::enquo(grouping_variable))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(outcome_variable), outcome_variable, NULL),
            `if`( ! missing(grouping_variable), grouping_variable, NULL))

    for (v in grouping_variable) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- jamovimdifftwoOptions$new(
        switch = switch,
        outcome_variable = outcome_variable,
        grouping_variable = grouping_variable,
        comparison_mean = comparison_mean,
        comparison_sd = comparison_sd,
        comparison_n = comparison_n,
        reference_mean = reference_mean,
        reference_sd = reference_sd,
        reference_n = reference_n,
        comparison_level_name = comparison_level_name,
        reference_level_name = reference_level_name,
        outcome_variable_name = outcome_variable_name,
        conf_level = conf_level,
        assume_equal_variance = assume_equal_variance)

    analysis <- jamovimdifftwoClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

