
# This file is automatically generated, you probably don't want to edit this

jamovimdiffindcontrastOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovimdiffindcontrastOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            switch = "from_raw",
            outcome_variable = NULL,
            grouping_variable = NULL,
            means = NULL,
            sds = NULL,
            ns = NULL,
            grouping_variable_levels = NULL,
            outcome_variable_name = "Outcome variable",
            grouping_variable_name = "Grouping variable",
            comparison_labels = " ",
            reference_labels = " ",
            conf_level = 95,
            assume_equal_variance = TRUE,
            show_details = FALSE, ...) {

            super$initialize(
                package="esci4",
                name="jamovimdiffindcontrast",
                requiresData=TRUE,
                ...)

            private$..switch <- jmvcore::OptionList$new(
                "switch",
                switch,
                default="from_raw",
                options=list(
                    "from_raw",
                    "from_summary"))
            private$..outcome_variable <- jmvcore::OptionVariables$new(
                "outcome_variable",
                outcome_variable,
                permitted=list(
                    "numeric"))
            private$..grouping_variable <- jmvcore::OptionVariable$new(
                "grouping_variable",
                grouping_variable,
                permitted=list(
                    "factor"))
            private$..means <- jmvcore::OptionVariable$new(
                "means",
                means,
                permitted=list(
                    "numeric"))
            private$..sds <- jmvcore::OptionVariable$new(
                "sds",
                sds,
                permitted=list(
                    "numeric"))
            private$..ns <- jmvcore::OptionVariable$new(
                "ns",
                ns,
                permitted=list(
                    "numeric"))
            private$..grouping_variable_levels <- jmvcore::OptionVariable$new(
                "grouping_variable_levels",
                grouping_variable_levels,
                permitted=list(
                    "factor"))
            private$..outcome_variable_name <- jmvcore::OptionString$new(
                "outcome_variable_name",
                outcome_variable_name,
                default="Outcome variable")
            private$..grouping_variable_name <- jmvcore::OptionString$new(
                "grouping_variable_name",
                grouping_variable_name,
                default="Grouping variable")
            private$..comparison_labels <- jmvcore::OptionString$new(
                "comparison_labels",
                comparison_labels,
                default=" ")
            private$..reference_labels <- jmvcore::OptionString$new(
                "reference_labels",
                reference_labels,
                default=" ")
            private$..conf_level <- jmvcore::OptionNumber$new(
                "conf_level",
                conf_level,
                min=1,
                max=99.999999,
                default=95)
            private$..assume_equal_variance <- jmvcore::OptionBool$new(
                "assume_equal_variance",
                assume_equal_variance,
                default=TRUE)
            private$..show_details <- jmvcore::OptionBool$new(
                "show_details",
                show_details,
                default=FALSE)

            self$.addOption(private$..switch)
            self$.addOption(private$..outcome_variable)
            self$.addOption(private$..grouping_variable)
            self$.addOption(private$..means)
            self$.addOption(private$..sds)
            self$.addOption(private$..ns)
            self$.addOption(private$..grouping_variable_levels)
            self$.addOption(private$..outcome_variable_name)
            self$.addOption(private$..grouping_variable_name)
            self$.addOption(private$..comparison_labels)
            self$.addOption(private$..reference_labels)
            self$.addOption(private$..conf_level)
            self$.addOption(private$..assume_equal_variance)
            self$.addOption(private$..show_details)
        }),
    active = list(
        switch = function() private$..switch$value,
        outcome_variable = function() private$..outcome_variable$value,
        grouping_variable = function() private$..grouping_variable$value,
        means = function() private$..means$value,
        sds = function() private$..sds$value,
        ns = function() private$..ns$value,
        grouping_variable_levels = function() private$..grouping_variable_levels$value,
        outcome_variable_name = function() private$..outcome_variable_name$value,
        grouping_variable_name = function() private$..grouping_variable_name$value,
        comparison_labels = function() private$..comparison_labels$value,
        reference_labels = function() private$..reference_labels$value,
        conf_level = function() private$..conf_level$value,
        assume_equal_variance = function() private$..assume_equal_variance$value,
        show_details = function() private$..show_details$value),
    private = list(
        ..switch = NA,
        ..outcome_variable = NA,
        ..grouping_variable = NA,
        ..means = NA,
        ..sds = NA,
        ..ns = NA,
        ..grouping_variable_levels = NA,
        ..outcome_variable_name = NA,
        ..grouping_variable_name = NA,
        ..comparison_labels = NA,
        ..reference_labels = NA,
        ..conf_level = NA,
        ..assume_equal_variance = NA,
        ..show_details = NA)
)

jamovimdiffindcontrastResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovimdiffindcontrastResults",
    inherit = jmvcore::Group,
    active = list(
        debug = function() private$.items[["debug"]],
        help = function() private$.items[["help"]],
        overview = function() private$.items[["overview"]],
        es_mean_difference = function() private$.items[["es_mean_difference"]],
        es_smd = function() private$.items[["es_smd"]],
        es_median_difference = function() private$.items[["es_median_difference"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Mdiff - Independent Groups Contrast")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="debug",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="help",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="overview",
                title="Overview",
                rows=1,
                clearWith=list(
                    "switch",
                    "grouping_variable_levels",
                    "means",
                    "sds",
                    "ns",
                    "outcome_variable_name",
                    "outcome_variable",
                    "grouping_variable",
                    "reference_levels",
                    "comparison_levels",
                    "conf_level",
                    "assume_equal_variance"),
                columns=list(
                    list(
                        `name`="outcome_variable_name", 
                        `title`="Outcome variable", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="grouping_variable_name", 
                        `title`="Grouping variable name", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="grouping_variable_level", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="mean", 
                        `type`="number", 
                        `title`="<i>M</i>"),
                    list(
                        `name`="mean_LL", 
                        `title`="LL", 
                        `type`="number"),
                    list(
                        `name`="mean_UL", 
                        `title`="UL", 
                        `type`="number"),
                    list(
                        `name`="median", 
                        `title`="Median", 
                        `type`="number", 
                        `visible`="(show_details & switch == 'from_raw')"),
                    list(
                        `name`="median_LL", 
                        `title`="LL", 
                        `type`="number", 
                        `visible`="(show_details & switch == 'from_raw')"),
                    list(
                        `name`="median_UL", 
                        `title`="UL", 
                        `type`="number", 
                        `visible`="(show_details & switch == 'from_raw')"),
                    list(
                        `name`="sd", 
                        `type`="number", 
                        `title`="<i>s</i>"),
                    list(
                        `name`="min", 
                        `title`="Minimum", 
                        `type`="number", 
                        `visible`="(show_details & switch == 'from_raw')"),
                    list(
                        `name`="max", 
                        `title`="Maximum", 
                        `type`="number", 
                        `visible`="(show_details & switch == 'from_raw')"),
                    list(
                        `name`="q1", 
                        `title`="25th", 
                        `type`="number", 
                        `superTitle`="Percentile", 
                        `visible`="(show_details & switch == 'from_raw')"),
                    list(
                        `name`="q3", 
                        `title`="75th", 
                        `type`="number", 
                        `superTitle`="Percentile", 
                        `visible`="(show_details & switch == 'from_raw')"),
                    list(
                        `name`="n", 
                        `title`="<i>n</i>", 
                        `type`="integer"),
                    list(
                        `name`="missing", 
                        `type`="integer", 
                        `title`="Missing", 
                        `visible`="(switch == 'from_raw')"),
                    list(
                        `name`="df_i", 
                        `title`="<i>df</i>", 
                        `type`="integer", 
                        `visible`="(show_details)"),
                    list(
                        `name`="mean_SE", 
                        `title`="<i>SE<sub>Mean</sub></i>", 
                        `type`="number", 
                        `visible`="(show_details)"),
                    list(
                        `name`="median_SE", 
                        `type`="number", 
                        `title`="<i>SE<sub>Median</sub></i>", 
                        `visible`="(show_details & switch == 'from_raw')"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="es_mean_difference",
                title="Mean difference",
                rows=3,
                clearWith=list(
                    "switch",
                    "grouping_variable_levels",
                    "means",
                    "sds",
                    "ns",
                    "outcome_variable_name",
                    "outcome_variable",
                    "grouping_variable",
                    "reference_levels",
                    "comparison_levels",
                    "conf_level",
                    "assume_equal_variance"),
                columns=list(
                    list(
                        `name`="outcome_variable_name", 
                        `title`="Outcome variable", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="grouping_variable_name", 
                        `title`="Grouping variable", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="effect", 
                        `title`="Effect", 
                        `type`="text"),
                    list(
                        `name`="effect_size", 
                        `type`="number", 
                        `title`="<i>M</i>"),
                    list(
                        `name`="LL", 
                        `title`="LL", 
                        `type`="number"),
                    list(
                        `name`="UL", 
                        `title`="UL", 
                        `type`="number"),
                    list(
                        `name`="SE", 
                        `title`="<i>SE</i>", 
                        `type`="number", 
                        `visible`="(show_details)"),
                    list(
                        `name`="df", 
                        `title`="<i>df</i>", 
                        `type`="number", 
                        `visible`="(show_details & !assume_equal_variance)"),
                    list(
                        `name`="df_i", 
                        `title`="<i>df</i>", 
                        `type`="integer", 
                        `visible`="(show_details & assume_equal_variance)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="es_smd",
                title="Standardized mean difference",
                rows=1,
                clearWith=list(
                    "switch",
                    "grouping_variable_levels",
                    "means",
                    "sds",
                    "ns",
                    "outcome_variable_name",
                    "outcome_variable",
                    "grouping_variable",
                    "reference_levels",
                    "comparison_levels",
                    "conf_level",
                    "assume_equal_variance"),
                columns=list(
                    list(
                        `name`="outcome_variable_name", 
                        `title`="Outcome variable", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="grouping_variable_name", 
                        `title`="Grouping variable", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="effect", 
                        `title`="Effect", 
                        `type`="text"),
                    list(
                        `name`="numerator", 
                        `title`="<i>M</i>", 
                        `type`="number"),
                    list(
                        `name`="denominator", 
                        `title`="Standardizer", 
                        `type`="number"),
                    list(
                        `name`="effect_size", 
                        `type`="number", 
                        `title`="<i>d</i>"),
                    list(
                        `name`="LL", 
                        `title`="LL", 
                        `type`="number"),
                    list(
                        `name`="UL", 
                        `title`="UL", 
                        `type`="number"),
                    list(
                        `name`="SE", 
                        `title`="<i>SE</i>", 
                        `type`="number", 
                        `visible`="(show_details)"),
                    list(
                        `name`="df", 
                        `title`="<i>df</i>", 
                        `type`="number", 
                        `visible`="(show_details & !assume_equal_variance)"),
                    list(
                        `name`="df_i", 
                        `title`="<i>df</i>", 
                        `type`="integer", 
                        `visible`="(show_details & assume_equal_variance)"),
                    list(
                        `name`="d_biased", 
                        `title`="<i>d</i><sub>biased</sub>", 
                        `type`="number", 
                        `visible`="(show_details)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="es_median_difference",
                title="Median difference",
                visible="(switch == 'from_raw')",
                rows=3,
                clearWith=list(
                    "switch",
                    "grouping_variable_levels",
                    "means",
                    "sds",
                    "ns",
                    "outcome_variable_name",
                    "outcome_variable",
                    "grouping_variable",
                    "reference_levels",
                    "comparison_levels",
                    "conf_level",
                    "assume_equal_variance"),
                columns=list(
                    list(
                        `name`="outcome_variable_name", 
                        `title`="Outcome variable", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="grouping_variable_name", 
                        `title`="Grouping variable", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="effect", 
                        `title`="Effect", 
                        `type`="text"),
                    list(
                        `name`="effect_size", 
                        `type`="number", 
                        `title`="<i>Mdn</i>"),
                    list(
                        `name`="LL", 
                        `title`="LL", 
                        `type`="number"),
                    list(
                        `name`="UL", 
                        `title`="UL", 
                        `type`="number"),
                    list(
                        `name`="SE", 
                        `title`="<i>SE</i>", 
                        `type`="number", 
                        `visible`="(show_details)"))))}))

jamovimdiffindcontrastBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovimdiffindcontrastBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "esci4",
                name = "jamovimdiffindcontrast",
                version = c(1,0,0),
                options = options,
                results = jamovimdiffindcontrastResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Mdiff - Independent Groups Contrast
#'
#' 
#' @param switch .
#' @param data .
#' @param outcome_variable .
#' @param grouping_variable .
#' @param means .
#' @param sds .
#' @param ns .
#' @param grouping_variable_levels .
#' @param outcome_variable_name .
#' @param grouping_variable_name .
#' @param comparison_labels .
#' @param reference_labels .
#' @param conf_level .
#' @param assume_equal_variance .
#' @param show_details .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$debug} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$help} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$overview} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$es_mean_difference} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$es_smd} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$es_median_difference} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$overview$asDF}
#'
#' \code{as.data.frame(results$overview)}
#'
#' @export
jamovimdiffindcontrast <- function(
    switch = "from_raw",
    data,
    outcome_variable,
    grouping_variable,
    means,
    sds,
    ns,
    grouping_variable_levels,
    outcome_variable_name = "Outcome variable",
    grouping_variable_name = "Grouping variable",
    comparison_labels = " ",
    reference_labels = " ",
    conf_level = 95,
    assume_equal_variance = TRUE,
    show_details = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jamovimdiffindcontrast requires jmvcore to be installed (restart may be required)")

    if ( ! missing(outcome_variable)) outcome_variable <- jmvcore::resolveQuo(jmvcore::enquo(outcome_variable))
    if ( ! missing(grouping_variable)) grouping_variable <- jmvcore::resolveQuo(jmvcore::enquo(grouping_variable))
    if ( ! missing(means)) means <- jmvcore::resolveQuo(jmvcore::enquo(means))
    if ( ! missing(sds)) sds <- jmvcore::resolveQuo(jmvcore::enquo(sds))
    if ( ! missing(ns)) ns <- jmvcore::resolveQuo(jmvcore::enquo(ns))
    if ( ! missing(grouping_variable_levels)) grouping_variable_levels <- jmvcore::resolveQuo(jmvcore::enquo(grouping_variable_levels))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(outcome_variable), outcome_variable, NULL),
            `if`( ! missing(grouping_variable), grouping_variable, NULL),
            `if`( ! missing(means), means, NULL),
            `if`( ! missing(sds), sds, NULL),
            `if`( ! missing(ns), ns, NULL),
            `if`( ! missing(grouping_variable_levels), grouping_variable_levels, NULL))

    for (v in grouping_variable) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in grouping_variable_levels) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- jamovimdiffindcontrastOptions$new(
        switch = switch,
        outcome_variable = outcome_variable,
        grouping_variable = grouping_variable,
        means = means,
        sds = sds,
        ns = ns,
        grouping_variable_levels = grouping_variable_levels,
        outcome_variable_name = outcome_variable_name,
        grouping_variable_name = grouping_variable_name,
        comparison_labels = comparison_labels,
        reference_labels = reference_labels,
        conf_level = conf_level,
        assume_equal_variance = assume_equal_variance,
        show_details = show_details)

    analysis <- jamovimdiffindcontrastClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

