
# This file is automatically generated, you probably don't want to edit this

jamovimdiffoneOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovimdiffoneOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            switch = "from_raw",
            outcome_variable = NULL,
            comparison_mean = NULL,
            comparison_sd = NULL,
            comparison_n = NULL,
            reference_mean = NULL,
            outcome_variable_name = "Outcome variable",
            conf_level = 95, ...) {

            super$initialize(
                package="esci4",
                name="jamovimdiffone",
                requiresData=TRUE,
                ...)

            private$..switch <- jmvcore::OptionList$new(
                "switch",
                switch,
                default="from_raw",
                options=list(
                    "from_raw",
                    "from_summary"))
            private$..outcome_variable <- jmvcore::OptionVariable$new(
                "outcome_variable",
                outcome_variable)
            private$..comparison_mean <- jmvcore::OptionNumber$new(
                "comparison_mean",
                comparison_mean)
            private$..comparison_sd <- jmvcore::OptionNumber$new(
                "comparison_sd",
                comparison_sd)
            private$..comparison_n <- jmvcore::OptionNumber$new(
                "comparison_n",
                comparison_n)
            private$..reference_mean <- jmvcore::OptionNumber$new(
                "reference_mean",
                reference_mean)
            private$..outcome_variable_name <- jmvcore::OptionString$new(
                "outcome_variable_name",
                outcome_variable_name,
                default="Outcome variable")
            private$..conf_level <- jmvcore::OptionNumber$new(
                "conf_level",
                conf_level,
                min=1,
                max=99.999999,
                default=95)

            self$.addOption(private$..switch)
            self$.addOption(private$..outcome_variable)
            self$.addOption(private$..comparison_mean)
            self$.addOption(private$..comparison_sd)
            self$.addOption(private$..comparison_n)
            self$.addOption(private$..reference_mean)
            self$.addOption(private$..outcome_variable_name)
            self$.addOption(private$..conf_level)
        }),
    active = list(
        switch = function() private$..switch$value,
        outcome_variable = function() private$..outcome_variable$value,
        comparison_mean = function() private$..comparison_mean$value,
        comparison_sd = function() private$..comparison_sd$value,
        comparison_n = function() private$..comparison_n$value,
        reference_mean = function() private$..reference_mean$value,
        outcome_variable_name = function() private$..outcome_variable_name$value,
        conf_level = function() private$..conf_level$value),
    private = list(
        ..switch = NA,
        ..outcome_variable = NA,
        ..comparison_mean = NA,
        ..comparison_sd = NA,
        ..comparison_n = NA,
        ..reference_mean = NA,
        ..outcome_variable_name = NA,
        ..conf_level = NA)
)

jamovimdiffoneResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovimdiffoneResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Mdiff - Single Group")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Mdiff - Single Group"))}))

jamovimdiffoneBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovimdiffoneBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "esci4",
                name = "jamovimdiffone",
                version = c(1,0,0),
                options = options,
                results = jamovimdiffoneResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Mdiff - Single Group
#'
#' 
#' @param switch .
#' @param data .
#' @param outcome_variable .
#' @param comparison_mean .
#' @param comparison_sd .
#' @param comparison_n .
#' @param reference_mean .
#' @param outcome_variable_name .
#' @param conf_level .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
jamovimdiffone <- function(
    switch = "from_raw",
    data,
    outcome_variable,
    comparison_mean,
    comparison_sd,
    comparison_n,
    reference_mean,
    outcome_variable_name = "Outcome variable",
    conf_level = 95) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jamovimdiffone requires jmvcore to be installed (restart may be required)")

    if ( ! missing(outcome_variable)) outcome_variable <- jmvcore::resolveQuo(jmvcore::enquo(outcome_variable))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(outcome_variable), outcome_variable, NULL))


    options <- jamovimdiffoneOptions$new(
        switch = switch,
        outcome_variable = outcome_variable,
        comparison_mean = comparison_mean,
        comparison_sd = comparison_sd,
        comparison_n = comparison_n,
        reference_mean = reference_mean,
        outcome_variable_name = outcome_variable_name,
        conf_level = conf_level)

    analysis <- jamovimdiffoneClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

