
# This file is automatically generated, you probably don't want to edit this

jamovimagnitudeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovimagnitudeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            outcome_variable = NULL,
            mean = NULL,
            sd = NULL,
            n = NULL,
            outcome_variable_name = "Outcome variable",
            conf_level = 95, ...) {

            super$initialize(
                package="esci4",
                name="jamovimagnitude",
                requiresData=TRUE,
                ...)

            private$..outcome_variable <- jmvcore::OptionVariable$new(
                "outcome_variable",
                outcome_variable,
                permitted=list(
                    "numeric"))
            private$..mean <- jmvcore::OptionNumber$new(
                "mean",
                mean)
            private$..sd <- jmvcore::OptionNumber$new(
                "sd",
                sd)
            private$..n <- jmvcore::OptionInteger$new(
                "n",
                n,
                min=1)
            private$..outcome_variable_name <- jmvcore::OptionString$new(
                "outcome_variable_name",
                outcome_variable_name,
                default="Outcome variable")
            private$..conf_level <- jmvcore::OptionNumber$new(
                "conf_level",
                conf_level,
                min=1,
                max=99.999999,
                default=95)

            self$.addOption(private$..outcome_variable)
            self$.addOption(private$..mean)
            self$.addOption(private$..sd)
            self$.addOption(private$..n)
            self$.addOption(private$..outcome_variable_name)
            self$.addOption(private$..conf_level)
        }),
    active = list(
        outcome_variable = function() private$..outcome_variable$value,
        mean = function() private$..mean$value,
        sd = function() private$..sd$value,
        n = function() private$..n$value,
        outcome_variable_name = function() private$..outcome_variable_name$value,
        conf_level = function() private$..conf_level$value),
    private = list(
        ..outcome_variable = NA,
        ..mean = NA,
        ..sd = NA,
        ..n = NA,
        ..outcome_variable_name = NA,
        ..conf_level = NA)
)

jamovimagnitudeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovimagnitudeResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Magnitude/Quantity")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Magnitude/Quantity"))}))

jamovimagnitudeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovimagnitudeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "esci4",
                name = "jamovimagnitude",
                version = c(1,0,0),
                options = options,
                results = jamovimagnitudeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Magnitude/Quantity
#'
#' 
#' @param data .
#' @param outcome_variable .
#' @param mean .
#' @param sd .
#' @param n .
#' @param outcome_variable_name .
#' @param conf_level .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
jamovimagnitude <- function(
    data,
    outcome_variable,
    mean,
    sd,
    n,
    outcome_variable_name = "Outcome variable",
    conf_level = 95) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jamovimagnitude requires jmvcore to be installed (restart may be required)")

    if ( ! missing(outcome_variable)) outcome_variable <- jmvcore::resolveQuo(jmvcore::enquo(outcome_variable))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(outcome_variable), outcome_variable, NULL))


    options <- jamovimagnitudeOptions$new(
        outcome_variable = outcome_variable,
        mean = mean,
        sd = sd,
        n = n,
        outcome_variable_name = outcome_variable_name,
        conf_level = conf_level)

    analysis <- jamovimagnitudeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

