
# This file is automatically generated, you probably don't want to edit this

jamovirmetarOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovirmetarOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rs = NULL,
            ns = NULL,
            labels = NULL,
            moderator = NULL,
            effect_label = "My effect",
            conf_level = 95,
            random_effects = TRUE,
            show_details = FALSE, ...) {

            super$initialize(
                package="esci4",
                name="jamovirmetar",
                requiresData=TRUE,
                ...)

            private$..rs <- jmvcore::OptionVariable$new(
                "rs",
                rs,
                permitted=list(
                    "numeric"))
            private$..ns <- jmvcore::OptionVariable$new(
                "ns",
                ns,
                permitted=list(
                    "numeric"))
            private$..labels <- jmvcore::OptionVariable$new(
                "labels",
                labels)
            private$..moderator <- jmvcore::OptionVariable$new(
                "moderator",
                moderator)
            private$..effect_label <- jmvcore::OptionString$new(
                "effect_label",
                effect_label,
                default="My effect")
            private$..conf_level <- jmvcore::OptionNumber$new(
                "conf_level",
                conf_level,
                min=1,
                max=99.999999,
                default=95)
            private$..random_effects <- jmvcore::OptionBool$new(
                "random_effects",
                random_effects,
                default=TRUE)
            private$..show_details <- jmvcore::OptionBool$new(
                "show_details",
                show_details,
                default=FALSE)

            self$.addOption(private$..rs)
            self$.addOption(private$..ns)
            self$.addOption(private$..labels)
            self$.addOption(private$..moderator)
            self$.addOption(private$..effect_label)
            self$.addOption(private$..conf_level)
            self$.addOption(private$..random_effects)
            self$.addOption(private$..show_details)
        }),
    active = list(
        rs = function() private$..rs$value,
        ns = function() private$..ns$value,
        labels = function() private$..labels$value,
        moderator = function() private$..moderator$value,
        effect_label = function() private$..effect_label$value,
        conf_level = function() private$..conf_level$value,
        random_effects = function() private$..random_effects$value,
        show_details = function() private$..show_details$value),
    private = list(
        ..rs = NA,
        ..ns = NA,
        ..labels = NA,
        ..moderator = NA,
        ..effect_label = NA,
        ..conf_level = NA,
        ..random_effects = NA,
        ..show_details = NA)
)

jamovirmetarResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovirmetarResults",
    inherit = jmvcore::Group,
    active = list(
        debug = function() private$.items[["debug"]],
        help = function() private$.items[["help"]],
        raw_data = function() private$.items[["raw_data"]],
        es_meta = function() private$.items[["es_meta"]],
        es_meta_difference = function() private$.items[["es_meta_difference"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Linear Correlation - Meta-analysis")
            self$add(jmvcore::Html$new(
                options=options,
                name="debug",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="help",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="raw_data",
                title="Overview",
                rows=1,
                columns=list(
                    list(
                        `name`="label", 
                        `title`="label", 
                        `type`="text"),
                    list(
                        `name`="moderator", 
                        `title`="Moderator level", 
                        `type`="text"),
                    list(
                        `name`="effect_size", 
                        `type`="number", 
                        `title`="<i>r</i>"),
                    list(
                        `name`="LL", 
                        `title`="LL", 
                        `type`="number"),
                    list(
                        `name`="UL", 
                        `title`="UL", 
                        `type`="number"),
                    list(
                        `name`="weight", 
                        `title`="weight", 
                        `type`="number", 
                        `visible`="(show_details)"),
                    list(
                        `name`="sample_variance", 
                        `title`="v2", 
                        `type`="number", 
                        `visible`="(show_details)"),
                    list(
                        `name`="SE", 
                        `title`="<i>SE</i>", 
                        `type`="number", 
                        `visible`="(show_details)"),
                    list(
                        `name`="r", 
                        `title`="<i>r</i>", 
                        `type`="number", 
                        `visible`="(show_details)"),
                    list(
                        `name`="N", 
                        `title`="<i>N</i>", 
                        `type`="integer", 
                        `visible`="(show_details)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="es_meta",
                title="Meta-analysis",
                rows=1,
                columns=list(
                    list(
                        `name`="effect_label", 
                        `title`="Effect", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="moderator_variable_name", 
                        `title`="Moderator", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="moderator_variable_level", 
                        `title`="Level", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="effect_size", 
                        `type`="number", 
                        `title`="<i>r</i>"),
                    list(
                        `name`="LL", 
                        `title`="LL", 
                        `type`="number"),
                    list(
                        `name`="UL", 
                        `title`="UL", 
                        `type`="number"),
                    list(
                        `name`="SE", 
                        `title`="<i>SE</i>", 
                        `type`="number", 
                        `visible`="(show_details)"),
                    list(
                        `name`="k", 
                        `type`="integer"),
                    list(
                        `name`="diamond_ratio", 
                        `type`="number"),
                    list(
                        `name`="diamond_ratio_LL", 
                        `type`="number"),
                    list(
                        `name`="diamond_ratio_UL", 
                        `type`="number"),
                    list(
                        `name`="I2", 
                        `type`="number"),
                    list(
                        `name`="I2_LL", 
                        `type`="number"),
                    list(
                        `name`="I2_UL", 
                        `type`="number"),
                    list(
                        `name`="FE_effect_size", 
                        `type`="number", 
                        `title`="Fixed effects effect size", 
                        `visible`="(show_details)"),
                    list(
                        `name`="RE_effect_size", 
                        `type`="number", 
                        `title`="Random effects effect size", 
                        `visible`="(show_details)"),
                    list(
                        `name`="FE_CI_width", 
                        `type`="number", 
                        `title`="Fixed effects CI width", 
                        `visible`="(show_details)"),
                    list(
                        `name`="RE_CI_width", 
                        `type`="number", 
                        `title`="Random effects CI width", 
                        `visible`="(show_details)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="es_meta_difference",
                title="Moderator analysis",
                rows=3,
                columns=list(
                    list(
                        `name`="effect_label", 
                        `title`="Effect", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="moderator_variable_name", 
                        `title`="Moderator", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="moderator_level", 
                        `title`="Level", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="effect_size", 
                        `type`="number", 
                        `title`="<i>r</i>"),
                    list(
                        `name`="LL", 
                        `title`="LL", 
                        `type`="number"),
                    list(
                        `name`="UL", 
                        `title`="UL", 
                        `type`="number"),
                    list(
                        `name`="SE", 
                        `title`="<i>SE</i>", 
                        `type`="number", 
                        `visible`="(show_details)"))))}))

jamovirmetarBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovirmetarBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "esci4",
                name = "jamovirmetar",
                version = c(1,0,0),
                options = options,
                results = jamovirmetarResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Linear Correlation - Meta-analysis
#'
#' 
#' @param data .
#' @param rs .
#' @param ns .
#' @param labels .
#' @param moderator .
#' @param effect_label .
#' @param conf_level .
#' @param random_effects .
#' @param show_details .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$debug} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$help} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$raw_data} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$es_meta} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$es_meta_difference} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$raw_data$asDF}
#'
#' \code{as.data.frame(results$raw_data)}
#'
#' @export
jamovirmetar <- function(
    data,
    rs,
    ns,
    labels,
    moderator,
    effect_label = "My effect",
    conf_level = 95,
    random_effects = TRUE,
    show_details = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jamovirmetar requires jmvcore to be installed (restart may be required)")

    if ( ! missing(rs)) rs <- jmvcore::resolveQuo(jmvcore::enquo(rs))
    if ( ! missing(ns)) ns <- jmvcore::resolveQuo(jmvcore::enquo(ns))
    if ( ! missing(labels)) labels <- jmvcore::resolveQuo(jmvcore::enquo(labels))
    if ( ! missing(moderator)) moderator <- jmvcore::resolveQuo(jmvcore::enquo(moderator))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rs), rs, NULL),
            `if`( ! missing(ns), ns, NULL),
            `if`( ! missing(labels), labels, NULL),
            `if`( ! missing(moderator), moderator, NULL))


    options <- jamovirmetarOptions$new(
        rs = rs,
        ns = ns,
        labels = labels,
        moderator = moderator,
        effect_label = effect_label,
        conf_level = conf_level,
        random_effects = random_effects,
        show_details = show_details)

    analysis <- jamovirmetarClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

