
# This file is automatically generated, you probably don't want to edit this

jamovirmetameanOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovirmetameanOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            means = NULL,
            sds = NULL,
            ns = NULL,
            labels = NULL,
            moderator = NULL,
            conf_level = 95,
            effect_label = "My effect",
            reference_mean = "0",
            reported_effect_size = "mean_difference",
            random_effects = "random_effects",
            show_details = FALSE,
            es_plot_width = "500",
            es_plot_height = "400",
            axis.text.y = "14",
            report_CIs = FALSE,
            meta_diamond_height = ".35",
            xlab = "auto",
            xmin = "auto",
            xmax = "auto",
            xbreaks = "auto",
            mark_zero = TRUE,
            axis.text.x = "14",
            axis.title.x = "15",
            dlab = "auto",
            dmin = "auto",
            dmax = "auto",
            dbreaks = "auto",
            shape_raw_reference = "square filled",
            shape_raw_comparison = "square filled",
            shape_raw_unused = "circle filled",
            color_raw_reference = "#008DF9",
            color_raw_comparison = "#009F81",
            color_raw_unused = "#009F81",
            color_summary_reference = "#008DF9",
            color_summary_comparison = "#009F81",
            color_summary_unused = "#009F81",
            color_summary_difference = "black",
            color_summary_overall = "black",
            fill_raw_reference = "NA",
            fill_raw_comparison = "NA",
            fill_raw_unused = "NA",
            fill_summary_reference = "#008DF9",
            fill_summary_comparison = "#009F81",
            fill_summary_unused = "#009F81",
            fill_summary_difference = "black",
            fill_summary_overall = "#009F81",
            size_raw_reference = "2",
            size_raw_comparison = "2",
            size_raw_unused = "2",
            alpha_raw_reference = "1",
            alpha_raw_comparison = "1",
            alpha_raw_unused = "1",
            alpha_summary_reference = "1",
            alpha_summary_comparison = "1",
            alpha_summary_unused = "1",
            alpha_summary_difference = "1",
            alpha_summary_overall = "1",
            linetype_raw_reference = "solid",
            linetype_raw_comparison = "solid",
            linetype_raw_unused = "solid",
            color_interval_reference = "black",
            color_interval_comparison = "black",
            color_interval_unused = "black",
            size_interval_reference = "3",
            size_interval_comparison = "3",
            size_interval_unused = "3",
            alpha_interval_reference = "1",
            alpha_interval_comparison = "1",
            alpha_interval_unused = "1", ...) {

            super$initialize(
                package="esci4",
                name="jamovirmetamean",
                requiresData=TRUE,
                ...)

            private$..means <- jmvcore::OptionVariable$new(
                "means",
                means,
                permitted=list(
                    "numeric"))
            private$..sds <- jmvcore::OptionVariable$new(
                "sds",
                sds,
                permitted=list(
                    "numeric"))
            private$..ns <- jmvcore::OptionVariable$new(
                "ns",
                ns,
                permitted=list(
                    "numeric"))
            private$..labels <- jmvcore::OptionVariable$new(
                "labels",
                labels)
            private$..moderator <- jmvcore::OptionVariable$new(
                "moderator",
                moderator)
            private$..conf_level <- jmvcore::OptionNumber$new(
                "conf_level",
                conf_level,
                default=95)
            private$..effect_label <- jmvcore::OptionString$new(
                "effect_label",
                effect_label,
                default="My effect")
            private$..reference_mean <- jmvcore::OptionString$new(
                "reference_mean",
                reference_mean,
                default="0")
            private$..reported_effect_size <- jmvcore::OptionList$new(
                "reported_effect_size",
                reported_effect_size,
                default="mean_difference",
                options=list(
                    "mean_difference",
                    "smd"))
            private$..random_effects <- jmvcore::OptionList$new(
                "random_effects",
                random_effects,
                default="random_effects",
                options=list(
                    "random_effects",
                    "fixed_effects"))
            private$..show_details <- jmvcore::OptionBool$new(
                "show_details",
                show_details,
                default=FALSE)
            private$..es_plot_width <- jmvcore::OptionString$new(
                "es_plot_width",
                es_plot_width,
                default="500")
            private$..es_plot_height <- jmvcore::OptionString$new(
                "es_plot_height",
                es_plot_height,
                default="400")
            private$..axis.text.y <- jmvcore::OptionString$new(
                "axis.text.y",
                axis.text.y,
                default="14")
            private$..report_CIs <- jmvcore::OptionBool$new(
                "report_CIs",
                report_CIs,
                default=FALSE)
            private$..meta_diamond_height <- jmvcore::OptionString$new(
                "meta_diamond_height",
                meta_diamond_height,
                default=".35")
            private$..xlab <- jmvcore::OptionString$new(
                "xlab",
                xlab,
                default="auto")
            private$..xmin <- jmvcore::OptionString$new(
                "xmin",
                xmin,
                default="auto")
            private$..xmax <- jmvcore::OptionString$new(
                "xmax",
                xmax,
                default="auto")
            private$..xbreaks <- jmvcore::OptionString$new(
                "xbreaks",
                xbreaks,
                default="auto")
            private$..mark_zero <- jmvcore::OptionBool$new(
                "mark_zero",
                mark_zero,
                default=TRUE)
            private$..axis.text.x <- jmvcore::OptionString$new(
                "axis.text.x",
                axis.text.x,
                default="14")
            private$..axis.title.x <- jmvcore::OptionString$new(
                "axis.title.x",
                axis.title.x,
                default="15")
            private$..dlab <- jmvcore::OptionString$new(
                "dlab",
                dlab,
                default="auto")
            private$..dmin <- jmvcore::OptionString$new(
                "dmin",
                dmin,
                default="auto")
            private$..dmax <- jmvcore::OptionString$new(
                "dmax",
                dmax,
                default="auto")
            private$..dbreaks <- jmvcore::OptionString$new(
                "dbreaks",
                dbreaks,
                default="auto")
            private$..shape_raw_reference <- jmvcore::OptionList$new(
                "shape_raw_reference",
                shape_raw_reference,
                default="square filled",
                options=list(
                    "circle filled",
                    "square filled",
                    "triangle filled",
                    "diamond filled"))
            private$..shape_raw_comparison <- jmvcore::OptionList$new(
                "shape_raw_comparison",
                shape_raw_comparison,
                default="square filled",
                options=list(
                    "circle filled",
                    "square filled",
                    "square filled",
                    "diamond filled"))
            private$..shape_raw_unused <- jmvcore::OptionList$new(
                "shape_raw_unused",
                shape_raw_unused,
                default="circle filled",
                options=list(
                    "circle filled",
                    "square filled",
                    "square filled",
                    "diamond filled"))
            private$..color_raw_reference <- jmvcore::OptionList$new(
                "color_raw_reference",
                color_raw_reference,
                default="#008DF9",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..color_raw_comparison <- jmvcore::OptionList$new(
                "color_raw_comparison",
                color_raw_comparison,
                default="#009F81",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..color_raw_unused <- jmvcore::OptionList$new(
                "color_raw_unused",
                color_raw_unused,
                default="#009F81",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..color_summary_reference <- jmvcore::OptionList$new(
                "color_summary_reference",
                color_summary_reference,
                default="#008DF9",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..color_summary_comparison <- jmvcore::OptionList$new(
                "color_summary_comparison",
                color_summary_comparison,
                default="#009F81",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..color_summary_unused <- jmvcore::OptionList$new(
                "color_summary_unused",
                color_summary_unused,
                default="#009F81",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..color_summary_difference <- jmvcore::OptionList$new(
                "color_summary_difference",
                color_summary_difference,
                default="black",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..color_summary_overall <- jmvcore::OptionList$new(
                "color_summary_overall",
                color_summary_overall,
                default="black",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..fill_raw_reference <- jmvcore::OptionList$new(
                "fill_raw_reference",
                fill_raw_reference,
                default="NA",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..fill_raw_comparison <- jmvcore::OptionList$new(
                "fill_raw_comparison",
                fill_raw_comparison,
                default="NA",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..fill_raw_unused <- jmvcore::OptionList$new(
                "fill_raw_unused",
                fill_raw_unused,
                default="NA",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..fill_summary_reference <- jmvcore::OptionList$new(
                "fill_summary_reference",
                fill_summary_reference,
                default="#008DF9",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..fill_summary_comparison <- jmvcore::OptionList$new(
                "fill_summary_comparison",
                fill_summary_comparison,
                default="#009F81",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..fill_summary_unused <- jmvcore::OptionList$new(
                "fill_summary_unused",
                fill_summary_unused,
                default="#009F81",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..fill_summary_difference <- jmvcore::OptionList$new(
                "fill_summary_difference",
                fill_summary_difference,
                default="black",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..fill_summary_overall <- jmvcore::OptionList$new(
                "fill_summary_overall",
                fill_summary_overall,
                default="#009F81",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..size_raw_reference <- jmvcore::OptionList$new(
                "size_raw_reference",
                size_raw_reference,
                default="2",
                options=list(
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6"))
            private$..size_raw_comparison <- jmvcore::OptionList$new(
                "size_raw_comparison",
                size_raw_comparison,
                default="2",
                options=list(
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6"))
            private$..size_raw_unused <- jmvcore::OptionList$new(
                "size_raw_unused",
                size_raw_unused,
                default="2",
                options=list(
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6"))
            private$..alpha_raw_reference <- jmvcore::OptionList$new(
                "alpha_raw_reference",
                alpha_raw_reference,
                default="1",
                options=list(
                    "1",
                    ".75",
                    ".5",
                    ".25",
                    "0"))
            private$..alpha_raw_comparison <- jmvcore::OptionList$new(
                "alpha_raw_comparison",
                alpha_raw_comparison,
                default="1",
                options=list(
                    "1",
                    ".75",
                    ".5",
                    ".25",
                    "0"))
            private$..alpha_raw_unused <- jmvcore::OptionList$new(
                "alpha_raw_unused",
                alpha_raw_unused,
                default="1",
                options=list(
                    "1",
                    ".75",
                    ".5",
                    ".25",
                    "0"))
            private$..alpha_summary_reference <- jmvcore::OptionList$new(
                "alpha_summary_reference",
                alpha_summary_reference,
                default="1",
                options=list(
                    "1",
                    ".75",
                    ".5",
                    ".25",
                    "0"))
            private$..alpha_summary_comparison <- jmvcore::OptionList$new(
                "alpha_summary_comparison",
                alpha_summary_comparison,
                default="1",
                options=list(
                    "1",
                    ".75",
                    ".5",
                    ".25",
                    "0"))
            private$..alpha_summary_unused <- jmvcore::OptionList$new(
                "alpha_summary_unused",
                alpha_summary_unused,
                default="1",
                options=list(
                    "1",
                    ".75",
                    ".5",
                    ".25",
                    "0"))
            private$..alpha_summary_difference <- jmvcore::OptionList$new(
                "alpha_summary_difference",
                alpha_summary_difference,
                default="1",
                options=list(
                    "1",
                    ".75",
                    ".5",
                    ".25",
                    "0"))
            private$..alpha_summary_overall <- jmvcore::OptionList$new(
                "alpha_summary_overall",
                alpha_summary_overall,
                default="1",
                options=list(
                    "1",
                    ".75",
                    ".5",
                    ".25",
                    "0"))
            private$..linetype_raw_reference <- jmvcore::OptionList$new(
                "linetype_raw_reference",
                linetype_raw_reference,
                default="solid",
                options=list(
                    "solid",
                    "dotted",
                    "dotdash",
                    "dashed",
                    "blank"))
            private$..linetype_raw_comparison <- jmvcore::OptionList$new(
                "linetype_raw_comparison",
                linetype_raw_comparison,
                default="solid",
                options=list(
                    "solid",
                    "dotted",
                    "dotdash",
                    "dashed",
                    "blank"))
            private$..linetype_raw_unused <- jmvcore::OptionList$new(
                "linetype_raw_unused",
                linetype_raw_unused,
                default="solid",
                options=list(
                    "solid",
                    "dotted",
                    "dotdash",
                    "dashed",
                    "blank"))
            private$..color_interval_reference <- jmvcore::OptionList$new(
                "color_interval_reference",
                color_interval_reference,
                default="black",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..color_interval_comparison <- jmvcore::OptionList$new(
                "color_interval_comparison",
                color_interval_comparison,
                default="black",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..color_interval_unused <- jmvcore::OptionList$new(
                "color_interval_unused",
                color_interval_unused,
                default="black",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..size_interval_reference <- jmvcore::OptionList$new(
                "size_interval_reference",
                size_interval_reference,
                default="3",
                options=list(
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",
                    "7",
                    "8"))
            private$..size_interval_comparison <- jmvcore::OptionList$new(
                "size_interval_comparison",
                size_interval_comparison,
                default="3",
                options=list(
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",
                    "7",
                    "8"))
            private$..size_interval_unused <- jmvcore::OptionList$new(
                "size_interval_unused",
                size_interval_unused,
                default="3",
                options=list(
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",
                    "7",
                    "8"))
            private$..alpha_interval_reference <- jmvcore::OptionList$new(
                "alpha_interval_reference",
                alpha_interval_reference,
                default="1",
                options=list(
                    "1",
                    ".75",
                    ".5",
                    ".25",
                    "0"))
            private$..alpha_interval_comparison <- jmvcore::OptionList$new(
                "alpha_interval_comparison",
                alpha_interval_comparison,
                default="1",
                options=list(
                    "1",
                    ".75",
                    ".5",
                    ".25",
                    "0"))
            private$..alpha_interval_unused <- jmvcore::OptionList$new(
                "alpha_interval_unused",
                alpha_interval_unused,
                default="1",
                options=list(
                    "1",
                    ".75",
                    ".5",
                    ".25",
                    "0"))

            self$.addOption(private$..means)
            self$.addOption(private$..sds)
            self$.addOption(private$..ns)
            self$.addOption(private$..labels)
            self$.addOption(private$..moderator)
            self$.addOption(private$..conf_level)
            self$.addOption(private$..effect_label)
            self$.addOption(private$..reference_mean)
            self$.addOption(private$..reported_effect_size)
            self$.addOption(private$..random_effects)
            self$.addOption(private$..show_details)
            self$.addOption(private$..es_plot_width)
            self$.addOption(private$..es_plot_height)
            self$.addOption(private$..axis.text.y)
            self$.addOption(private$..report_CIs)
            self$.addOption(private$..meta_diamond_height)
            self$.addOption(private$..xlab)
            self$.addOption(private$..xmin)
            self$.addOption(private$..xmax)
            self$.addOption(private$..xbreaks)
            self$.addOption(private$..mark_zero)
            self$.addOption(private$..axis.text.x)
            self$.addOption(private$..axis.title.x)
            self$.addOption(private$..dlab)
            self$.addOption(private$..dmin)
            self$.addOption(private$..dmax)
            self$.addOption(private$..dbreaks)
            self$.addOption(private$..shape_raw_reference)
            self$.addOption(private$..shape_raw_comparison)
            self$.addOption(private$..shape_raw_unused)
            self$.addOption(private$..color_raw_reference)
            self$.addOption(private$..color_raw_comparison)
            self$.addOption(private$..color_raw_unused)
            self$.addOption(private$..color_summary_reference)
            self$.addOption(private$..color_summary_comparison)
            self$.addOption(private$..color_summary_unused)
            self$.addOption(private$..color_summary_difference)
            self$.addOption(private$..color_summary_overall)
            self$.addOption(private$..fill_raw_reference)
            self$.addOption(private$..fill_raw_comparison)
            self$.addOption(private$..fill_raw_unused)
            self$.addOption(private$..fill_summary_reference)
            self$.addOption(private$..fill_summary_comparison)
            self$.addOption(private$..fill_summary_unused)
            self$.addOption(private$..fill_summary_difference)
            self$.addOption(private$..fill_summary_overall)
            self$.addOption(private$..size_raw_reference)
            self$.addOption(private$..size_raw_comparison)
            self$.addOption(private$..size_raw_unused)
            self$.addOption(private$..alpha_raw_reference)
            self$.addOption(private$..alpha_raw_comparison)
            self$.addOption(private$..alpha_raw_unused)
            self$.addOption(private$..alpha_summary_reference)
            self$.addOption(private$..alpha_summary_comparison)
            self$.addOption(private$..alpha_summary_unused)
            self$.addOption(private$..alpha_summary_difference)
            self$.addOption(private$..alpha_summary_overall)
            self$.addOption(private$..linetype_raw_reference)
            self$.addOption(private$..linetype_raw_comparison)
            self$.addOption(private$..linetype_raw_unused)
            self$.addOption(private$..color_interval_reference)
            self$.addOption(private$..color_interval_comparison)
            self$.addOption(private$..color_interval_unused)
            self$.addOption(private$..size_interval_reference)
            self$.addOption(private$..size_interval_comparison)
            self$.addOption(private$..size_interval_unused)
            self$.addOption(private$..alpha_interval_reference)
            self$.addOption(private$..alpha_interval_comparison)
            self$.addOption(private$..alpha_interval_unused)
        }),
    active = list(
        means = function() private$..means$value,
        sds = function() private$..sds$value,
        ns = function() private$..ns$value,
        labels = function() private$..labels$value,
        moderator = function() private$..moderator$value,
        conf_level = function() private$..conf_level$value,
        effect_label = function() private$..effect_label$value,
        reference_mean = function() private$..reference_mean$value,
        reported_effect_size = function() private$..reported_effect_size$value,
        random_effects = function() private$..random_effects$value,
        show_details = function() private$..show_details$value,
        es_plot_width = function() private$..es_plot_width$value,
        es_plot_height = function() private$..es_plot_height$value,
        axis.text.y = function() private$..axis.text.y$value,
        report_CIs = function() private$..report_CIs$value,
        meta_diamond_height = function() private$..meta_diamond_height$value,
        xlab = function() private$..xlab$value,
        xmin = function() private$..xmin$value,
        xmax = function() private$..xmax$value,
        xbreaks = function() private$..xbreaks$value,
        mark_zero = function() private$..mark_zero$value,
        axis.text.x = function() private$..axis.text.x$value,
        axis.title.x = function() private$..axis.title.x$value,
        dlab = function() private$..dlab$value,
        dmin = function() private$..dmin$value,
        dmax = function() private$..dmax$value,
        dbreaks = function() private$..dbreaks$value,
        shape_raw_reference = function() private$..shape_raw_reference$value,
        shape_raw_comparison = function() private$..shape_raw_comparison$value,
        shape_raw_unused = function() private$..shape_raw_unused$value,
        color_raw_reference = function() private$..color_raw_reference$value,
        color_raw_comparison = function() private$..color_raw_comparison$value,
        color_raw_unused = function() private$..color_raw_unused$value,
        color_summary_reference = function() private$..color_summary_reference$value,
        color_summary_comparison = function() private$..color_summary_comparison$value,
        color_summary_unused = function() private$..color_summary_unused$value,
        color_summary_difference = function() private$..color_summary_difference$value,
        color_summary_overall = function() private$..color_summary_overall$value,
        fill_raw_reference = function() private$..fill_raw_reference$value,
        fill_raw_comparison = function() private$..fill_raw_comparison$value,
        fill_raw_unused = function() private$..fill_raw_unused$value,
        fill_summary_reference = function() private$..fill_summary_reference$value,
        fill_summary_comparison = function() private$..fill_summary_comparison$value,
        fill_summary_unused = function() private$..fill_summary_unused$value,
        fill_summary_difference = function() private$..fill_summary_difference$value,
        fill_summary_overall = function() private$..fill_summary_overall$value,
        size_raw_reference = function() private$..size_raw_reference$value,
        size_raw_comparison = function() private$..size_raw_comparison$value,
        size_raw_unused = function() private$..size_raw_unused$value,
        alpha_raw_reference = function() private$..alpha_raw_reference$value,
        alpha_raw_comparison = function() private$..alpha_raw_comparison$value,
        alpha_raw_unused = function() private$..alpha_raw_unused$value,
        alpha_summary_reference = function() private$..alpha_summary_reference$value,
        alpha_summary_comparison = function() private$..alpha_summary_comparison$value,
        alpha_summary_unused = function() private$..alpha_summary_unused$value,
        alpha_summary_difference = function() private$..alpha_summary_difference$value,
        alpha_summary_overall = function() private$..alpha_summary_overall$value,
        linetype_raw_reference = function() private$..linetype_raw_reference$value,
        linetype_raw_comparison = function() private$..linetype_raw_comparison$value,
        linetype_raw_unused = function() private$..linetype_raw_unused$value,
        color_interval_reference = function() private$..color_interval_reference$value,
        color_interval_comparison = function() private$..color_interval_comparison$value,
        color_interval_unused = function() private$..color_interval_unused$value,
        size_interval_reference = function() private$..size_interval_reference$value,
        size_interval_comparison = function() private$..size_interval_comparison$value,
        size_interval_unused = function() private$..size_interval_unused$value,
        alpha_interval_reference = function() private$..alpha_interval_reference$value,
        alpha_interval_comparison = function() private$..alpha_interval_comparison$value,
        alpha_interval_unused = function() private$..alpha_interval_unused$value),
    private = list(
        ..means = NA,
        ..sds = NA,
        ..ns = NA,
        ..labels = NA,
        ..moderator = NA,
        ..conf_level = NA,
        ..effect_label = NA,
        ..reference_mean = NA,
        ..reported_effect_size = NA,
        ..random_effects = NA,
        ..show_details = NA,
        ..es_plot_width = NA,
        ..es_plot_height = NA,
        ..axis.text.y = NA,
        ..report_CIs = NA,
        ..meta_diamond_height = NA,
        ..xlab = NA,
        ..xmin = NA,
        ..xmax = NA,
        ..xbreaks = NA,
        ..mark_zero = NA,
        ..axis.text.x = NA,
        ..axis.title.x = NA,
        ..dlab = NA,
        ..dmin = NA,
        ..dmax = NA,
        ..dbreaks = NA,
        ..shape_raw_reference = NA,
        ..shape_raw_comparison = NA,
        ..shape_raw_unused = NA,
        ..color_raw_reference = NA,
        ..color_raw_comparison = NA,
        ..color_raw_unused = NA,
        ..color_summary_reference = NA,
        ..color_summary_comparison = NA,
        ..color_summary_unused = NA,
        ..color_summary_difference = NA,
        ..color_summary_overall = NA,
        ..fill_raw_reference = NA,
        ..fill_raw_comparison = NA,
        ..fill_raw_unused = NA,
        ..fill_summary_reference = NA,
        ..fill_summary_comparison = NA,
        ..fill_summary_unused = NA,
        ..fill_summary_difference = NA,
        ..fill_summary_overall = NA,
        ..size_raw_reference = NA,
        ..size_raw_comparison = NA,
        ..size_raw_unused = NA,
        ..alpha_raw_reference = NA,
        ..alpha_raw_comparison = NA,
        ..alpha_raw_unused = NA,
        ..alpha_summary_reference = NA,
        ..alpha_summary_comparison = NA,
        ..alpha_summary_unused = NA,
        ..alpha_summary_difference = NA,
        ..alpha_summary_overall = NA,
        ..linetype_raw_reference = NA,
        ..linetype_raw_comparison = NA,
        ..linetype_raw_unused = NA,
        ..color_interval_reference = NA,
        ..color_interval_comparison = NA,
        ..color_interval_unused = NA,
        ..size_interval_reference = NA,
        ..size_interval_comparison = NA,
        ..size_interval_unused = NA,
        ..alpha_interval_reference = NA,
        ..alpha_interval_comparison = NA,
        ..alpha_interval_unused = NA)
)

jamovirmetameanResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovirmetameanResults",
    inherit = jmvcore::Group,
    active = list(
        debug = function() private$.items[["debug"]],
        help = function() private$.items[["help"]],
        raw_data = function() private$.items[["raw_data"]],
        es_meta = function() private$.items[["es_meta"]],
        es_meta_difference = function() private$.items[["es_meta_difference"]],
        estimation_plot_warnings = function() private$.items[["estimation_plot_warnings"]],
        estimation_plots = function() private$.items[["estimation_plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Meta-Analysis: Means")
            self$add(jmvcore::Html$new(
                options=options,
                name="debug",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="help",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="raw_data",
                title="Overview",
                rows=1,
                columns=list(
                    list(
                        `name`="label", 
                        `title`="label", 
                        `type`="text"),
                    list(
                        `name`="moderator", 
                        `title`="Moderator level", 
                        `type`="text"),
                    list(
                        `name`="effect_size", 
                        `type`="number", 
                        `title`="<i>M</i>", 
                        `visible`="(reported_effect_size == \"mean_difference\")"),
                    list(
                        `name`="effect_size_smd", 
                        `type`="number", 
                        `title`="<i>d</i><sub>1</sub>", 
                        `visible`="(reported_effect_size == \"smd\")"),
                    list(
                        `name`="LL", 
                        `title`="LL", 
                        `type`="number"),
                    list(
                        `name`="UL", 
                        `title`="UL", 
                        `type`="number"),
                    list(
                        `name`="weight", 
                        `title`="weight", 
                        `type`="number", 
                        `visible`="(show_details)"),
                    list(
                        `name`="sample_variance", 
                        `title`="v2", 
                        `type`="number", 
                        `visible`="(show_details)"),
                    list(
                        `name`="SE", 
                        `title`="<i>SE</i>", 
                        `type`="number", 
                        `visible`="(show_details)"),
                    list(
                        `name`="mean", 
                        `title`="<i>M</i>", 
                        `type`="number", 
                        `visible`="(show_details)"),
                    list(
                        `name`="sd", 
                        `title`="<i>s</i>", 
                        `type`="number", 
                        `visible`="(show_details)"),
                    list(
                        `name`="n", 
                        `title`="<i>N</i>", 
                        `type`="integer", 
                        `visible`="(show_details)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="es_meta",
                title="Meta-analysis",
                rows=1,
                columns=list(
                    list(
                        `name`="effect_label", 
                        `title`="Effect", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="moderator_variable_name", 
                        `title`="Moderator", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="moderator_variable_level", 
                        `title`="Level", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="effect_size", 
                        `type`="number", 
                        `title`="<i>M</i>", 
                        `visible`="(reported_effect_size == \"mean_difference\")"),
                    list(
                        `name`="effect_size_smd", 
                        `type`="number", 
                        `title`="<i>d</i><sub>1</sub>", 
                        `visible`="(reported_effect_size == \"smd\")"),
                    list(
                        `name`="LL", 
                        `title`="LL", 
                        `type`="number"),
                    list(
                        `name`="UL", 
                        `title`="UL", 
                        `type`="number"),
                    list(
                        `name`="SE", 
                        `title`="<i>SE</i>", 
                        `type`="number", 
                        `visible`="(show_details)"),
                    list(
                        `name`="k", 
                        `type`="integer", 
                        `title`="<i>k</i>"),
                    list(
                        `name`="diamond_ratio", 
                        `type`="number", 
                        `title`="Diamond ratio"),
                    list(
                        `name`="diamond_ratio_LL", 
                        `title`="LL", 
                        `type`="number"),
                    list(
                        `name`="diamond_ratio_UL", 
                        `type`="number", 
                        `title`="UL"),
                    list(
                        `name`="I2", 
                        `type`="number", 
                        `title`="<i>I</i><sup>2</sup>"),
                    list(
                        `name`="I2_LL", 
                        `type`="number", 
                        `title`="LL"),
                    list(
                        `name`="I2_UL", 
                        `type`="number", 
                        `title`="UL"),
                    list(
                        `name`="FE_effect_size", 
                        `type`="number", 
                        `title`="Fixed effects effect size", 
                        `visible`="(show_details)"),
                    list(
                        `name`="RE_effect_size", 
                        `type`="number", 
                        `title`="Random effects effect size", 
                        `visible`="(show_details)"),
                    list(
                        `name`="FE_CI_width", 
                        `type`="number", 
                        `title`="Fixed effects CI width", 
                        `visible`="(show_details)"),
                    list(
                        `name`="RE_CI_width", 
                        `type`="number", 
                        `title`="Random effects CI width", 
                        `visible`="(show_details)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="es_meta_difference",
                title="Moderator Analysis",
                rows=3,
                columns=list(
                    list(
                        `name`="effect_label", 
                        `title`="Effect", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="moderator_variable_name", 
                        `title`="Moderator", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="moderator_level", 
                        `title`="Level", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="effect_size", 
                        `type`="number", 
                        `title`="<i>M</i>", 
                        `visible`="(reported_effect_size == \"mean_difference\")"),
                    list(
                        `name`="effect_size_smd", 
                        `type`="number", 
                        `title`="<i>d</i><sub>1</sub>", 
                        `visible`="(reported_effect_size == \"smd\")"),
                    list(
                        `name`="LL", 
                        `title`="LL", 
                        `type`="number"),
                    list(
                        `name`="UL", 
                        `title`="UL", 
                        `type`="number"),
                    list(
                        `name`="SE", 
                        `title`="<i>SE</i>", 
                        `type`="number", 
                        `visible`="(show_details)"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="estimation_plot_warnings",
                title="Estimation Figure Warnings",
                visible=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="estimation_plots",
                title="Estimation Figure",
                requiresData=TRUE,
                width=400,
                height=300,
                renderFun=".estimation_plots"))}))

jamovirmetameanBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovirmetameanBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "esci4",
                name = "jamovirmetamean",
                version = c(1,0,0),
                options = options,
                results = jamovirmetameanResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Means
#'
#' 
#' @param data .
#' @param means .
#' @param sds .
#' @param ns .
#' @param labels .
#' @param moderator .
#' @param conf_level .
#' @param effect_label .
#' @param reference_mean .
#' @param reported_effect_size .
#' @param random_effects .
#' @param show_details .
#' @param es_plot_width .
#' @param es_plot_height .
#' @param axis.text.y .
#' @param report_CIs .
#' @param meta_diamond_height .
#' @param xlab .
#' @param xmin .
#' @param xmax .
#' @param xbreaks .
#' @param mark_zero .
#' @param axis.text.x .
#' @param axis.title.x .
#' @param dlab .
#' @param dmin .
#' @param dmax .
#' @param dbreaks .
#' @param shape_raw_reference .
#' @param shape_raw_comparison .
#' @param shape_raw_unused .
#' @param color_raw_reference .
#' @param color_raw_comparison .
#' @param color_raw_unused .
#' @param color_summary_reference .
#' @param color_summary_comparison .
#' @param color_summary_unused .
#' @param color_summary_difference .
#' @param color_summary_overall .
#' @param fill_raw_reference .
#' @param fill_raw_comparison .
#' @param fill_raw_unused .
#' @param fill_summary_reference .
#' @param fill_summary_comparison .
#' @param fill_summary_unused .
#' @param fill_summary_difference .
#' @param fill_summary_overall .
#' @param size_raw_reference .
#' @param size_raw_comparison .
#' @param size_raw_unused .
#' @param alpha_raw_reference .
#' @param alpha_raw_comparison .
#' @param alpha_raw_unused .
#' @param alpha_summary_reference .
#' @param alpha_summary_comparison .
#' @param alpha_summary_unused .
#' @param alpha_summary_difference .
#' @param alpha_summary_overall .
#' @param linetype_raw_reference .
#' @param linetype_raw_comparison .
#' @param linetype_raw_unused .
#' @param color_interval_reference .
#' @param color_interval_comparison .
#' @param color_interval_unused .
#' @param size_interval_reference .
#' @param size_interval_comparison .
#' @param size_interval_unused .
#' @param alpha_interval_reference .
#' @param alpha_interval_comparison .
#' @param alpha_interval_unused .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$debug} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$help} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$raw_data} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$es_meta} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$es_meta_difference} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$estimation_plot_warnings} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$estimation_plots} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$raw_data$asDF}
#'
#' \code{as.data.frame(results$raw_data)}
#'
#' @export
jamovirmetamean <- function(
    data,
    means,
    sds,
    ns,
    labels,
    moderator,
    conf_level = 95,
    effect_label = "My effect",
    reference_mean = "0",
    reported_effect_size = "mean_difference",
    random_effects = "random_effects",
    show_details = FALSE,
    es_plot_width = "500",
    es_plot_height = "400",
    axis.text.y = "14",
    report_CIs = FALSE,
    meta_diamond_height = ".35",
    xlab = "auto",
    xmin = "auto",
    xmax = "auto",
    xbreaks = "auto",
    mark_zero = TRUE,
    axis.text.x = "14",
    axis.title.x = "15",
    dlab = "auto",
    dmin = "auto",
    dmax = "auto",
    dbreaks = "auto",
    shape_raw_reference = "square filled",
    shape_raw_comparison = "square filled",
    shape_raw_unused = "circle filled",
    color_raw_reference = "#008DF9",
    color_raw_comparison = "#009F81",
    color_raw_unused = "#009F81",
    color_summary_reference = "#008DF9",
    color_summary_comparison = "#009F81",
    color_summary_unused = "#009F81",
    color_summary_difference = "black",
    color_summary_overall = "black",
    fill_raw_reference = "NA",
    fill_raw_comparison = "NA",
    fill_raw_unused = "NA",
    fill_summary_reference = "#008DF9",
    fill_summary_comparison = "#009F81",
    fill_summary_unused = "#009F81",
    fill_summary_difference = "black",
    fill_summary_overall = "#009F81",
    size_raw_reference = "2",
    size_raw_comparison = "2",
    size_raw_unused = "2",
    alpha_raw_reference = "1",
    alpha_raw_comparison = "1",
    alpha_raw_unused = "1",
    alpha_summary_reference = "1",
    alpha_summary_comparison = "1",
    alpha_summary_unused = "1",
    alpha_summary_difference = "1",
    alpha_summary_overall = "1",
    linetype_raw_reference = "solid",
    linetype_raw_comparison = "solid",
    linetype_raw_unused = "solid",
    color_interval_reference = "black",
    color_interval_comparison = "black",
    color_interval_unused = "black",
    size_interval_reference = "3",
    size_interval_comparison = "3",
    size_interval_unused = "3",
    alpha_interval_reference = "1",
    alpha_interval_comparison = "1",
    alpha_interval_unused = "1") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jamovirmetamean requires jmvcore to be installed (restart may be required)")

    if ( ! missing(means)) means <- jmvcore::resolveQuo(jmvcore::enquo(means))
    if ( ! missing(sds)) sds <- jmvcore::resolveQuo(jmvcore::enquo(sds))
    if ( ! missing(ns)) ns <- jmvcore::resolveQuo(jmvcore::enquo(ns))
    if ( ! missing(labels)) labels <- jmvcore::resolveQuo(jmvcore::enquo(labels))
    if ( ! missing(moderator)) moderator <- jmvcore::resolveQuo(jmvcore::enquo(moderator))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(means), means, NULL),
            `if`( ! missing(sds), sds, NULL),
            `if`( ! missing(ns), ns, NULL),
            `if`( ! missing(labels), labels, NULL),
            `if`( ! missing(moderator), moderator, NULL))


    options <- jamovirmetameanOptions$new(
        means = means,
        sds = sds,
        ns = ns,
        labels = labels,
        moderator = moderator,
        conf_level = conf_level,
        effect_label = effect_label,
        reference_mean = reference_mean,
        reported_effect_size = reported_effect_size,
        random_effects = random_effects,
        show_details = show_details,
        es_plot_width = es_plot_width,
        es_plot_height = es_plot_height,
        axis.text.y = axis.text.y,
        report_CIs = report_CIs,
        meta_diamond_height = meta_diamond_height,
        xlab = xlab,
        xmin = xmin,
        xmax = xmax,
        xbreaks = xbreaks,
        mark_zero = mark_zero,
        axis.text.x = axis.text.x,
        axis.title.x = axis.title.x,
        dlab = dlab,
        dmin = dmin,
        dmax = dmax,
        dbreaks = dbreaks,
        shape_raw_reference = shape_raw_reference,
        shape_raw_comparison = shape_raw_comparison,
        shape_raw_unused = shape_raw_unused,
        color_raw_reference = color_raw_reference,
        color_raw_comparison = color_raw_comparison,
        color_raw_unused = color_raw_unused,
        color_summary_reference = color_summary_reference,
        color_summary_comparison = color_summary_comparison,
        color_summary_unused = color_summary_unused,
        color_summary_difference = color_summary_difference,
        color_summary_overall = color_summary_overall,
        fill_raw_reference = fill_raw_reference,
        fill_raw_comparison = fill_raw_comparison,
        fill_raw_unused = fill_raw_unused,
        fill_summary_reference = fill_summary_reference,
        fill_summary_comparison = fill_summary_comparison,
        fill_summary_unused = fill_summary_unused,
        fill_summary_difference = fill_summary_difference,
        fill_summary_overall = fill_summary_overall,
        size_raw_reference = size_raw_reference,
        size_raw_comparison = size_raw_comparison,
        size_raw_unused = size_raw_unused,
        alpha_raw_reference = alpha_raw_reference,
        alpha_raw_comparison = alpha_raw_comparison,
        alpha_raw_unused = alpha_raw_unused,
        alpha_summary_reference = alpha_summary_reference,
        alpha_summary_comparison = alpha_summary_comparison,
        alpha_summary_unused = alpha_summary_unused,
        alpha_summary_difference = alpha_summary_difference,
        alpha_summary_overall = alpha_summary_overall,
        linetype_raw_reference = linetype_raw_reference,
        linetype_raw_comparison = linetype_raw_comparison,
        linetype_raw_unused = linetype_raw_unused,
        color_interval_reference = color_interval_reference,
        color_interval_comparison = color_interval_comparison,
        color_interval_unused = color_interval_unused,
        size_interval_reference = size_interval_reference,
        size_interval_comparison = size_interval_comparison,
        size_interval_unused = size_interval_unused,
        alpha_interval_reference = alpha_interval_reference,
        alpha_interval_comparison = alpha_interval_comparison,
        alpha_interval_unused = alpha_interval_unused)

    analysis <- jamovirmetameanClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

