
# This file is automatically generated, you probably don't want to edit this

jamovirmetameanOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovirmetameanOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            means = NULL,
            sds = NULL,
            ns = NULL,
            labels = NULL,
            moderator = NULL,
            reference_mean = "0",
            effect_label = "My effect",
            reported_effect_size = "mean_difference",
            conf_level = 95,
            random_effects = TRUE,
            show_details = FALSE, ...) {

            super$initialize(
                package="esci4",
                name="jamovirmetamean",
                requiresData=TRUE,
                ...)

            private$..means <- jmvcore::OptionVariable$new(
                "means",
                means,
                permitted=list(
                    "numeric"))
            private$..sds <- jmvcore::OptionVariable$new(
                "sds",
                sds,
                permitted=list(
                    "numeric"))
            private$..ns <- jmvcore::OptionVariable$new(
                "ns",
                ns,
                permitted=list(
                    "numeric"))
            private$..labels <- jmvcore::OptionVariable$new(
                "labels",
                labels)
            private$..moderator <- jmvcore::OptionVariable$new(
                "moderator",
                moderator)
            private$..reference_mean <- jmvcore::OptionString$new(
                "reference_mean",
                reference_mean,
                default="0")
            private$..effect_label <- jmvcore::OptionString$new(
                "effect_label",
                effect_label,
                default="My effect")
            private$..reported_effect_size <- jmvcore::OptionList$new(
                "reported_effect_size",
                reported_effect_size,
                default="mean_difference",
                options=list(
                    "mean_difference",
                    "smd"))
            private$..conf_level <- jmvcore::OptionNumber$new(
                "conf_level",
                conf_level,
                default=95)
            private$..random_effects <- jmvcore::OptionBool$new(
                "random_effects",
                random_effects,
                default=TRUE)
            private$..show_details <- jmvcore::OptionBool$new(
                "show_details",
                show_details,
                default=FALSE)

            self$.addOption(private$..means)
            self$.addOption(private$..sds)
            self$.addOption(private$..ns)
            self$.addOption(private$..labels)
            self$.addOption(private$..moderator)
            self$.addOption(private$..reference_mean)
            self$.addOption(private$..effect_label)
            self$.addOption(private$..reported_effect_size)
            self$.addOption(private$..conf_level)
            self$.addOption(private$..random_effects)
            self$.addOption(private$..show_details)
        }),
    active = list(
        means = function() private$..means$value,
        sds = function() private$..sds$value,
        ns = function() private$..ns$value,
        labels = function() private$..labels$value,
        moderator = function() private$..moderator$value,
        reference_mean = function() private$..reference_mean$value,
        effect_label = function() private$..effect_label$value,
        reported_effect_size = function() private$..reported_effect_size$value,
        conf_level = function() private$..conf_level$value,
        random_effects = function() private$..random_effects$value,
        show_details = function() private$..show_details$value),
    private = list(
        ..means = NA,
        ..sds = NA,
        ..ns = NA,
        ..labels = NA,
        ..moderator = NA,
        ..reference_mean = NA,
        ..effect_label = NA,
        ..reported_effect_size = NA,
        ..conf_level = NA,
        ..random_effects = NA,
        ..show_details = NA)
)

jamovirmetameanResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovirmetameanResults",
    inherit = jmvcore::Group,
    active = list(
        debug = function() private$.items[["debug"]],
        help = function() private$.items[["help"]],
        raw_data = function() private$.items[["raw_data"]],
        es_meta = function() private$.items[["es_meta"]],
        es_meta_difference = function() private$.items[["es_meta_difference"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Meta-Analysis: Means")
            self$add(jmvcore::Html$new(
                options=options,
                name="debug",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="help",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="raw_data",
                title="Overview",
                rows=1,
                columns=list(
                    list(
                        `name`="label", 
                        `title`="label", 
                        `type`="text"),
                    list(
                        `name`="moderator", 
                        `title`="Moderator level", 
                        `type`="text"),
                    list(
                        `name`="effect_size", 
                        `type`="number", 
                        `title`="<i>M</i>", 
                        `visible`="(reported_effect_size == \"mean_difference\")"),
                    list(
                        `name`="effect_size_smd", 
                        `type`="number", 
                        `title`="<i>d</i><sub>1 - corrected</sub>", 
                        `visible`="(reported_effect_size == \"smd\")"),
                    list(
                        `name`="LL", 
                        `title`="LL", 
                        `type`="number"),
                    list(
                        `name`="UL", 
                        `title`="UL", 
                        `type`="number"),
                    list(
                        `name`="weight", 
                        `title`="weight", 
                        `type`="number", 
                        `visible`="(show_details)"),
                    list(
                        `name`="sample_variance", 
                        `title`="v2", 
                        `type`="number", 
                        `visible`="(show_details)"),
                    list(
                        `name`="SE", 
                        `title`="<i>SE</i>", 
                        `type`="number", 
                        `visible`="(show_details)"),
                    list(
                        `name`="mean", 
                        `title`="<i>M</i>", 
                        `type`="number", 
                        `visible`="(show_details)"),
                    list(
                        `name`="sd", 
                        `title`="<i>s</i>", 
                        `type`="number", 
                        `visible`="(show_details)"),
                    list(
                        `name`="n", 
                        `title`="<i>N</i>", 
                        `type`="integer", 
                        `visible`="(show_details)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="es_meta",
                title="Meta-analysis",
                rows=1,
                columns=list(
                    list(
                        `name`="effect_label", 
                        `title`="Effect", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="moderator_variable_name", 
                        `title`="Moderator", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="moderator_variable_level", 
                        `title`="Level", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="effect_size", 
                        `type`="number", 
                        `title`="<i>M</i>", 
                        `visible`="(reported_effect_size == \"mean_difference\")"),
                    list(
                        `name`="effect_size_smd", 
                        `type`="number", 
                        `title`="<i>d</i><sub>1 - corrected</sub>", 
                        `visible`="(reported_effect_size == \"smd\")"),
                    list(
                        `name`="LL", 
                        `title`="LL", 
                        `type`="number"),
                    list(
                        `name`="UL", 
                        `title`="UL", 
                        `type`="number"),
                    list(
                        `name`="SE", 
                        `title`="<i>SE</i>", 
                        `type`="number", 
                        `visible`="(show_details)"),
                    list(
                        `name`="k", 
                        `type`="integer"),
                    list(
                        `name`="diamond_ratio", 
                        `type`="number"),
                    list(
                        `name`="diamond_ratio_LL", 
                        `type`="number"),
                    list(
                        `name`="diamond_ratio_UL", 
                        `type`="number"),
                    list(
                        `name`="I2", 
                        `type`="number"),
                    list(
                        `name`="I2_LL", 
                        `type`="number"),
                    list(
                        `name`="I2_UL", 
                        `type`="number"),
                    list(
                        `name`="FE_effect_size", 
                        `type`="number", 
                        `title`="Fixed effects effect size", 
                        `visible`="(show_details)"),
                    list(
                        `name`="RE_effect_size", 
                        `type`="number", 
                        `title`="Random effects effect size", 
                        `visible`="(show_details)"),
                    list(
                        `name`="FE_CI_width", 
                        `type`="number", 
                        `title`="Fixed effects CI width", 
                        `visible`="(show_details)"),
                    list(
                        `name`="RE_CI_width", 
                        `type`="number", 
                        `title`="Random effects CI width", 
                        `visible`="(show_details)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="es_meta_difference",
                title="Moderator Analysis",
                rows=3,
                columns=list(
                    list(
                        `name`="effect_label", 
                        `title`="Effect", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="moderator_variable_name", 
                        `title`="Moderator", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="moderator_level", 
                        `title`="Level", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="effect_size", 
                        `type`="number", 
                        `title`="<i>M</i>", 
                        `visible`="(reported_effect_size == \"mean_difference\")"),
                    list(
                        `name`="effect_size_smd", 
                        `type`="number", 
                        `title`="<i>d</i><sub>1 - corrected</sub>", 
                        `visible`="(reported_effect_size == \"smd\")"),
                    list(
                        `name`="LL", 
                        `title`="LL", 
                        `type`="number"),
                    list(
                        `name`="UL", 
                        `title`="UL", 
                        `type`="number"),
                    list(
                        `name`="SE", 
                        `title`="<i>SE</i>", 
                        `type`="number", 
                        `visible`="(show_details)"))))}))

jamovirmetameanBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovirmetameanBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "esci4",
                name = "jamovirmetamean",
                version = c(1,0,0),
                options = options,
                results = jamovirmetameanResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Means
#'
#' 
#' @param data .
#' @param means .
#' @param sds .
#' @param ns .
#' @param labels .
#' @param moderator .
#' @param reference_mean .
#' @param effect_label .
#' @param reported_effect_size .
#' @param conf_level .
#' @param random_effects .
#' @param show_details .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$debug} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$help} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$raw_data} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$es_meta} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$es_meta_difference} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$raw_data$asDF}
#'
#' \code{as.data.frame(results$raw_data)}
#'
#' @export
jamovirmetamean <- function(
    data,
    means,
    sds,
    ns,
    labels,
    moderator,
    reference_mean = "0",
    effect_label = "My effect",
    reported_effect_size = "mean_difference",
    conf_level = 95,
    random_effects = TRUE,
    show_details = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jamovirmetamean requires jmvcore to be installed (restart may be required)")

    if ( ! missing(means)) means <- jmvcore::resolveQuo(jmvcore::enquo(means))
    if ( ! missing(sds)) sds <- jmvcore::resolveQuo(jmvcore::enquo(sds))
    if ( ! missing(ns)) ns <- jmvcore::resolveQuo(jmvcore::enquo(ns))
    if ( ! missing(labels)) labels <- jmvcore::resolveQuo(jmvcore::enquo(labels))
    if ( ! missing(moderator)) moderator <- jmvcore::resolveQuo(jmvcore::enquo(moderator))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(means), means, NULL),
            `if`( ! missing(sds), sds, NULL),
            `if`( ! missing(ns), ns, NULL),
            `if`( ! missing(labels), labels, NULL),
            `if`( ! missing(moderator), moderator, NULL))


    options <- jamovirmetameanOptions$new(
        means = means,
        sds = sds,
        ns = ns,
        labels = labels,
        moderator = moderator,
        reference_mean = reference_mean,
        effect_label = effect_label,
        reported_effect_size = reported_effect_size,
        conf_level = conf_level,
        random_effects = random_effects,
        show_details = show_details)

    analysis <- jamovirmetameanClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

