
# This file is automatically generated, you probably don't want to edit this

jamovipdiffoneOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovipdiffoneOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            switch = "from_raw",
            outcome_variable = NULL,
            comparison_cases = " ",
            comparison_n = " ",
            reference_p = " ",
            raw_case_label = "1",
            summary_case_label = "Affected",
            outcome_variable_name = "Outcome variable",
            count_NA = FALSE,
            conf_level = 95,
            show_details = FALSE, ...) {

            super$initialize(
                package="esci4",
                name="jamovipdiffone",
                requiresData=TRUE,
                ...)

            private$..switch <- jmvcore::OptionList$new(
                "switch",
                switch,
                default="from_raw",
                options=list(
                    "from_raw",
                    "from_summary"))
            private$..outcome_variable <- jmvcore::OptionVariables$new(
                "outcome_variable",
                outcome_variable)
            private$..comparison_cases <- jmvcore::OptionString$new(
                "comparison_cases",
                comparison_cases,
                default=" ")
            private$..comparison_n <- jmvcore::OptionString$new(
                "comparison_n",
                comparison_n,
                default=" ")
            private$..reference_p <- jmvcore::OptionString$new(
                "reference_p",
                reference_p,
                default=" ")
            private$..raw_case_label <- jmvcore::OptionString$new(
                "raw_case_label",
                raw_case_label,
                default="1")
            private$..summary_case_label <- jmvcore::OptionString$new(
                "summary_case_label",
                summary_case_label,
                default="Affected")
            private$..outcome_variable_name <- jmvcore::OptionString$new(
                "outcome_variable_name",
                outcome_variable_name,
                default="Outcome variable")
            private$..count_NA <- jmvcore::OptionBool$new(
                "count_NA",
                count_NA,
                default=FALSE)
            private$..conf_level <- jmvcore::OptionNumber$new(
                "conf_level",
                conf_level,
                min=1,
                max=99.999999,
                default=95)
            private$..show_details <- jmvcore::OptionBool$new(
                "show_details",
                show_details,
                default=FALSE)

            self$.addOption(private$..switch)
            self$.addOption(private$..outcome_variable)
            self$.addOption(private$..comparison_cases)
            self$.addOption(private$..comparison_n)
            self$.addOption(private$..reference_p)
            self$.addOption(private$..raw_case_label)
            self$.addOption(private$..summary_case_label)
            self$.addOption(private$..outcome_variable_name)
            self$.addOption(private$..count_NA)
            self$.addOption(private$..conf_level)
            self$.addOption(private$..show_details)
        }),
    active = list(
        switch = function() private$..switch$value,
        outcome_variable = function() private$..outcome_variable$value,
        comparison_cases = function() private$..comparison_cases$value,
        comparison_n = function() private$..comparison_n$value,
        reference_p = function() private$..reference_p$value,
        raw_case_label = function() private$..raw_case_label$value,
        summary_case_label = function() private$..summary_case_label$value,
        outcome_variable_name = function() private$..outcome_variable_name$value,
        count_NA = function() private$..count_NA$value,
        conf_level = function() private$..conf_level$value,
        show_details = function() private$..show_details$value),
    private = list(
        ..switch = NA,
        ..outcome_variable = NA,
        ..comparison_cases = NA,
        ..comparison_n = NA,
        ..reference_p = NA,
        ..raw_case_label = NA,
        ..summary_case_label = NA,
        ..outcome_variable_name = NA,
        ..count_NA = NA,
        ..conf_level = NA,
        ..show_details = NA)
)

jamovipdiffoneResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovipdiffoneResults",
    inherit = jmvcore::Group,
    active = list(
        debug = function() private$.items[["debug"]],
        help = function() private$.items[["help"]],
        overview = function() private$.items[["overview"]],
        es_proportion_difference = function() private$.items[["es_proportion_difference"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Pdiff - Single Group")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="debug",
                visible=TRUE))
            self$add(jmvcore::Html$new(
                options=options,
                name="help",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="overview",
                title="Overview",
                rows=1,
                columns=list(
                    list(
                        `name`="outcome_variable_name", 
                        `title`="Outcome variable", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="outcome_variable_level", 
                        `type`="text", 
                        `title`="Level"),
                    list(
                        `name`="cases", 
                        `title`="Cases", 
                        `type`="integer"),
                    list(
                        `name`="n", 
                        `title`="<i>N</i>", 
                        `type`="integer"),
                    list(
                        `name`="P", 
                        `title`="<i>P</i>", 
                        `type`="number"),
                    list(
                        `name`="P_LL", 
                        `title`="LL", 
                        `type`="number"),
                    list(
                        `name`="P_UL", 
                        `title`="UL", 
                        `type`="number"),
                    list(
                        `name`="P_SE", 
                        `type`="number", 
                        `title`="<i>SE<sub>P</sub></i>", 
                        `visible`="(show_details)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="es_proportion_difference",
                title="Proportion difference",
                rows=2,
                columns=list(
                    list(
                        `name`="outcome_variable_name", 
                        `title`="Outcome variable", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="effect", 
                        `title`="Effect", 
                        `type`="text"),
                    list(
                        `name`="effect_size", 
                        `type`="number", 
                        `title`="<i>P</i>"),
                    list(
                        `name`="LL", 
                        `title`="LL", 
                        `type`="number"),
                    list(
                        `name`="UL", 
                        `title`="UL", 
                        `type`="number"),
                    list(
                        `name`="SE", 
                        `title`="<i>SE</i>", 
                        `type`="number", 
                        `visible`="(show_details)"),
                    list(
                        `name`="cases", 
                        `title`="<i>Cases</i>", 
                        `type`="integer", 
                        `visible`="(show_details)"),
                    list(
                        `name`="n", 
                        `title`="<i>N</i>", 
                        `type`="integer", 
                        `visible`="(show_details)"))))}))

jamovipdiffoneBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovipdiffoneBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "esci4",
                name = "jamovipdiffone",
                version = c(1,0,0),
                options = options,
                results = jamovipdiffoneResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Pdiff - Single Group
#'
#' 
#' @param switch .
#' @param data .
#' @param outcome_variable .
#' @param comparison_cases .
#' @param comparison_n .
#' @param reference_p .
#' @param raw_case_label .
#' @param summary_case_label .
#' @param outcome_variable_name .
#' @param count_NA .
#' @param conf_level .
#' @param show_details .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$debug} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$help} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$overview} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$es_proportion_difference} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$overview$asDF}
#'
#' \code{as.data.frame(results$overview)}
#'
#' @export
jamovipdiffone <- function(
    switch = "from_raw",
    data,
    outcome_variable,
    comparison_cases = " ",
    comparison_n = " ",
    reference_p = " ",
    raw_case_label = "1",
    summary_case_label = "Affected",
    outcome_variable_name = "Outcome variable",
    count_NA = FALSE,
    conf_level = 95,
    show_details = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jamovipdiffone requires jmvcore to be installed (restart may be required)")

    if ( ! missing(outcome_variable)) outcome_variable <- jmvcore::resolveQuo(jmvcore::enquo(outcome_variable))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(outcome_variable), outcome_variable, NULL))


    options <- jamovipdiffoneOptions$new(
        switch = switch,
        outcome_variable = outcome_variable,
        comparison_cases = comparison_cases,
        comparison_n = comparison_n,
        reference_p = reference_p,
        raw_case_label = raw_case_label,
        summary_case_label = summary_case_label,
        outcome_variable_name = outcome_variable_name,
        count_NA = count_NA,
        conf_level = conf_level,
        show_details = show_details)

    analysis <- jamovipdiffoneClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

