
# This file is automatically generated, you probably don't want to edit this

jamovimagnitudeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovimagnitudeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            switch = "from_raw",
            outcome_variable = NULL,
            mean = "",
            sd = "",
            n = "",
            outcome_variable_name = "Outcome variable",
            conf_level = 95,
            show_details = FALSE,
            es_plot_width = "450",
            es_plot_height = "450",
            ymin = "auto",
            ymax = "auto",
            breaks = "auto",
            ylab = "auto",
            xlab = "auto",
            axis.text.y = "10",
            axis.title.y = "12",
            axis.text.x = "10",
            axis.title.x = "12",
            error_layout = "halfeye",
            error_scale = "0.25",
            error_nudge = "0.4",
            data_layout = "random",
            data_spread = "0.25",
            shape_raw = "circle filled",
            shape_summary = "circle filled",
            color_raw = "gray",
            color_summary = "black",
            fill_raw = "white",
            fill_summary = "black",
            size_raw = "2",
            size_summary = "3",
            alpha_raw = "1",
            alpha_summary = "1",
            linetype_summary = "solid",
            color_interval = "black",
            size_interval = "1",
            alpha_interval = "1",
            alpha_error = "1",
            fill_error = "gray", ...) {

            super$initialize(
                package="esci4",
                name="jamovimagnitude",
                requiresData=TRUE,
                ...)

            private$..switch <- jmvcore::OptionList$new(
                "switch",
                switch,
                default="from_raw",
                options=list(
                    "from_raw",
                    "from_summary"))
            private$..outcome_variable <- jmvcore::OptionVariables$new(
                "outcome_variable",
                outcome_variable,
                permitted=list(
                    "numeric"))
            private$..mean <- jmvcore::OptionString$new(
                "mean",
                mean,
                default="")
            private$..sd <- jmvcore::OptionString$new(
                "sd",
                sd,
                default="")
            private$..n <- jmvcore::OptionString$new(
                "n",
                n,
                default="")
            private$..outcome_variable_name <- jmvcore::OptionString$new(
                "outcome_variable_name",
                outcome_variable_name,
                default="Outcome variable")
            private$..conf_level <- jmvcore::OptionNumber$new(
                "conf_level",
                conf_level,
                min=1,
                max=99.999999,
                default=95)
            private$..show_details <- jmvcore::OptionBool$new(
                "show_details",
                show_details,
                default=FALSE)
            private$..es_plot_width <- jmvcore::OptionString$new(
                "es_plot_width",
                es_plot_width,
                default="450")
            private$..es_plot_height <- jmvcore::OptionString$new(
                "es_plot_height",
                es_plot_height,
                default="450")
            private$..ymin <- jmvcore::OptionString$new(
                "ymin",
                ymin,
                default="auto")
            private$..ymax <- jmvcore::OptionString$new(
                "ymax",
                ymax,
                default="auto")
            private$..breaks <- jmvcore::OptionString$new(
                "breaks",
                breaks,
                default="auto")
            private$..ylab <- jmvcore::OptionString$new(
                "ylab",
                ylab,
                default="auto")
            private$..xlab <- jmvcore::OptionString$new(
                "xlab",
                xlab,
                default="auto")
            private$..axis.text.y <- jmvcore::OptionString$new(
                "axis.text.y",
                axis.text.y,
                default="10")
            private$..axis.title.y <- jmvcore::OptionString$new(
                "axis.title.y",
                axis.title.y,
                default="12")
            private$..axis.text.x <- jmvcore::OptionString$new(
                "axis.text.x",
                axis.text.x,
                default="10")
            private$..axis.title.x <- jmvcore::OptionString$new(
                "axis.title.x",
                axis.title.x,
                default="12")
            private$..error_layout <- jmvcore::OptionList$new(
                "error_layout",
                error_layout,
                default="halfeye",
                options=list(
                    "halfeye",
                    "eye",
                    "none"))
            private$..error_scale <- jmvcore::OptionString$new(
                "error_scale",
                error_scale,
                default="0.25")
            private$..error_nudge <- jmvcore::OptionString$new(
                "error_nudge",
                error_nudge,
                default="0.4")
            private$..data_layout <- jmvcore::OptionList$new(
                "data_layout",
                data_layout,
                default="random",
                options=list(
                    "random",
                    "swarm",
                    "none"))
            private$..data_spread <- jmvcore::OptionString$new(
                "data_spread",
                data_spread,
                default="0.25")
            private$..shape_raw <- jmvcore::OptionList$new(
                "shape_raw",
                shape_raw,
                default="circle filled",
                options=list(
                    "circle filled",
                    "square filled",
                    "triangle filled",
                    "diamond filled"))
            private$..shape_summary <- jmvcore::OptionList$new(
                "shape_summary",
                shape_summary,
                default="circle filled",
                options=list(
                    "circle filled",
                    "square filled",
                    "triangle filled",
                    "diamond filled"))
            private$..color_raw <- jmvcore::OptionList$new(
                "color_raw",
                color_raw,
                default="gray",
                options=list(
                    "white",
                    "aliceblue",
                    "antiquewhite",
                    "aquamarine",
                    "azure",
                    "beige",
                    "bisque",
                    "black",
                    "blanchedalmond",
                    "blue",
                    "blueviolet",
                    "brown",
                    "burlywood",
                    "cadetblue",
                    "chartreuse",
                    "chocolate",
                    "coral",
                    "cornflowerblue",
                    "cornsilk",
                    "cyan",
                    "deeppink",
                    "deepskyblue",
                    "dimgray",
                    "dimgrey",
                    "dodgerblue",
                    "firebrick",
                    "floralwhite",
                    "forestgreen",
                    "gainsboro",
                    "ghostwhite",
                    "gold",
                    "goldenrod",
                    "gray",
                    "green",
                    "greenyellow",
                    "grey",
                    "honeydew",
                    "hotpink",
                    "indianred",
                    "ivory",
                    "khaki",
                    "lavender",
                    "lavenderblush",
                    "lawngreen",
                    "lemonchiffon",
                    "limegreen",
                    "linen",
                    "magenta",
                    "maroon",
                    "midnightblue",
                    "mintcream",
                    "mistyrose",
                    "moccasin",
                    "navajowhite",
                    "navy",
                    "navyblue",
                    "oldlace",
                    "olivedrab",
                    "orange",
                    "orangered",
                    "orchid",
                    "palegoldenrod",
                    "palegreen",
                    "paleturquoise",
                    "palevioletred",
                    "papayawhip",
                    "peachpuff",
                    "peru",
                    "pink",
                    "plum",
                    "powderblue",
                    "purple",
                    "red",
                    "rosybrown",
                    "royalblue",
                    "saddlebrown",
                    "salmon",
                    "sandybrown",
                    "seagreen",
                    "seashell",
                    "sienna",
                    "skyblue",
                    "slateblue",
                    "slategray",
                    "slategrey",
                    "snow",
                    "springgreen",
                    "steelblue",
                    "tan",
                    "thistle",
                    "tomato",
                    "turquoise",
                    "violet",
                    "violetred",
                    "wheat",
                    "whitesmoke",
                    "yellow",
                    "yellowgreen"))
            private$..color_summary <- jmvcore::OptionList$new(
                "color_summary",
                color_summary,
                default="black",
                options=list(
                    "white",
                    "aliceblue",
                    "antiquewhite",
                    "aquamarine",
                    "azure",
                    "beige",
                    "bisque",
                    "black",
                    "blanchedalmond",
                    "blue",
                    "blueviolet",
                    "brown",
                    "burlywood",
                    "cadetblue",
                    "chartreuse",
                    "chocolate",
                    "coral",
                    "cornflowerblue",
                    "cornsilk",
                    "cyan",
                    "deeppink",
                    "deepskyblue",
                    "dimgray",
                    "dimgrey",
                    "dodgerblue",
                    "firebrick",
                    "floralwhite",
                    "forestgreen",
                    "gainsboro",
                    "ghostwhite",
                    "gold",
                    "goldenrod",
                    "gray",
                    "green",
                    "greenyellow",
                    "grey",
                    "honeydew",
                    "hotpink",
                    "indianred",
                    "ivory",
                    "khaki",
                    "lavender",
                    "lavenderblush",
                    "lawngreen",
                    "lemonchiffon",
                    "limegreen",
                    "linen",
                    "magenta",
                    "maroon",
                    "midnightblue",
                    "mintcream",
                    "mistyrose",
                    "moccasin",
                    "navajowhite",
                    "navy",
                    "navyblue",
                    "oldlace",
                    "olivedrab",
                    "orange",
                    "orangered",
                    "orchid",
                    "palegoldenrod",
                    "palegreen",
                    "paleturquoise",
                    "palevioletred",
                    "papayawhip",
                    "peachpuff",
                    "peru",
                    "pink",
                    "plum",
                    "powderblue",
                    "purple",
                    "red",
                    "rosybrown",
                    "royalblue",
                    "saddlebrown",
                    "salmon",
                    "sandybrown",
                    "seagreen",
                    "seashell",
                    "sienna",
                    "skyblue",
                    "slateblue",
                    "slategray",
                    "slategrey",
                    "snow",
                    "springgreen",
                    "steelblue",
                    "tan",
                    "thistle",
                    "tomato",
                    "turquoise",
                    "violet",
                    "violetred",
                    "wheat",
                    "whitesmoke",
                    "yellow",
                    "yellowgreen"))
            private$..fill_raw <- jmvcore::OptionList$new(
                "fill_raw",
                fill_raw,
                default="white",
                options=list(
                    "NA",
                    "white",
                    "aliceblue",
                    "antiquewhite",
                    "aquamarine",
                    "azure",
                    "beige",
                    "bisque",
                    "black",
                    "blanchedalmond",
                    "blue",
                    "blueviolet",
                    "brown",
                    "burlywood",
                    "cadetblue",
                    "chartreuse",
                    "chocolate",
                    "coral",
                    "cornflowerblue",
                    "cornsilk",
                    "cyan",
                    "deeppink",
                    "deepskyblue",
                    "dimgray",
                    "dimgrey",
                    "dodgerblue",
                    "firebrick",
                    "floralwhite",
                    "forestgreen",
                    "gainsboro",
                    "ghostwhite",
                    "gold",
                    "goldenrod",
                    "gray",
                    "green",
                    "greenyellow",
                    "grey",
                    "honeydew",
                    "hotpink",
                    "indianred",
                    "ivory",
                    "khaki",
                    "lavender",
                    "lavenderblush",
                    "lawngreen",
                    "lemonchiffon",
                    "limegreen",
                    "linen",
                    "magenta",
                    "maroon",
                    "midnightblue",
                    "mintcream",
                    "mistyrose",
                    "moccasin",
                    "navajowhite",
                    "navy",
                    "navyblue",
                    "oldlace",
                    "olivedrab",
                    "orange",
                    "orangered",
                    "orchid",
                    "palegoldenrod",
                    "palegreen",
                    "paleturquoise",
                    "palevioletred",
                    "papayawhip",
                    "peachpuff",
                    "peru",
                    "pink",
                    "plum",
                    "powderblue",
                    "purple",
                    "red",
                    "rosybrown",
                    "royalblue",
                    "saddlebrown",
                    "salmon",
                    "sandybrown",
                    "seagreen",
                    "seashell",
                    "sienna",
                    "skyblue",
                    "slateblue",
                    "slategray",
                    "slategrey",
                    "snow",
                    "springgreen",
                    "steelblue",
                    "tan",
                    "thistle",
                    "tomato",
                    "turquoise",
                    "violet",
                    "violetred",
                    "wheat",
                    "whitesmoke",
                    "yellow",
                    "yellowgreen"))
            private$..fill_summary <- jmvcore::OptionList$new(
                "fill_summary",
                fill_summary,
                default="black",
                options=list(
                    "NA",
                    "white",
                    "aliceblue",
                    "antiquewhite",
                    "aquamarine",
                    "azure",
                    "beige",
                    "bisque",
                    "black",
                    "blanchedalmond",
                    "blue",
                    "blueviolet",
                    "brown",
                    "burlywood",
                    "cadetblue",
                    "chartreuse",
                    "chocolate",
                    "coral",
                    "cornflowerblue",
                    "cornsilk",
                    "cyan",
                    "deeppink",
                    "deepskyblue",
                    "dimgray",
                    "dimgrey",
                    "dodgerblue",
                    "firebrick",
                    "floralwhite",
                    "forestgreen",
                    "gainsboro",
                    "ghostwhite",
                    "gold",
                    "goldenrod",
                    "gray",
                    "green",
                    "greenyellow",
                    "grey",
                    "honeydew",
                    "hotpink",
                    "indianred",
                    "ivory",
                    "khaki",
                    "lavender",
                    "lavenderblush",
                    "lawngreen",
                    "lemonchiffon",
                    "limegreen",
                    "linen",
                    "magenta",
                    "maroon",
                    "midnightblue",
                    "mintcream",
                    "mistyrose",
                    "moccasin",
                    "navajowhite",
                    "navy",
                    "navyblue",
                    "oldlace",
                    "olivedrab",
                    "orange",
                    "orangered",
                    "orchid",
                    "palegoldenrod",
                    "palegreen",
                    "paleturquoise",
                    "palevioletred",
                    "papayawhip",
                    "peachpuff",
                    "peru",
                    "pink",
                    "plum",
                    "powderblue",
                    "purple",
                    "red",
                    "rosybrown",
                    "royalblue",
                    "saddlebrown",
                    "salmon",
                    "sandybrown",
                    "seagreen",
                    "seashell",
                    "sienna",
                    "skyblue",
                    "slateblue",
                    "slategray",
                    "slategrey",
                    "snow",
                    "springgreen",
                    "steelblue",
                    "tan",
                    "thistle",
                    "tomato",
                    "turquoise",
                    "violet",
                    "violetred",
                    "wheat",
                    "whitesmoke",
                    "yellow",
                    "yellowgreen"))
            private$..size_raw <- jmvcore::OptionList$new(
                "size_raw",
                size_raw,
                default="2",
                options=list(
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6"))
            private$..size_summary <- jmvcore::OptionList$new(
                "size_summary",
                size_summary,
                default="3",
                options=list(
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6"))
            private$..alpha_raw <- jmvcore::OptionList$new(
                "alpha_raw",
                alpha_raw,
                default="1",
                options=list(
                    "1",
                    ".75",
                    ".5",
                    ".25",
                    "0"))
            private$..alpha_summary <- jmvcore::OptionList$new(
                "alpha_summary",
                alpha_summary,
                default="1",
                options=list(
                    "1",
                    ".75",
                    ".5",
                    ".25",
                    "0"))
            private$..linetype_summary <- jmvcore::OptionList$new(
                "linetype_summary",
                linetype_summary,
                default="solid",
                options=list(
                    "solid",
                    "dotted",
                    "dotdash",
                    "dashed",
                    "blank"))
            private$..color_interval <- jmvcore::OptionList$new(
                "color_interval",
                color_interval,
                default="black",
                options=list(
                    "white",
                    "aliceblue",
                    "antiquewhite",
                    "aquamarine",
                    "azure",
                    "beige",
                    "bisque",
                    "black",
                    "blanchedalmond",
                    "blue",
                    "blueviolet",
                    "brown",
                    "burlywood",
                    "cadetblue",
                    "chartreuse",
                    "chocolate",
                    "coral",
                    "cornflowerblue",
                    "cornsilk",
                    "cyan",
                    "deeppink",
                    "deepskyblue",
                    "dimgray",
                    "dimgrey",
                    "dodgerblue",
                    "firebrick",
                    "floralwhite",
                    "forestgreen",
                    "gainsboro",
                    "ghostwhite",
                    "gold",
                    "goldenrod",
                    "gray",
                    "green",
                    "greenyellow",
                    "grey",
                    "honeydew",
                    "hotpink",
                    "indianred",
                    "ivory",
                    "khaki",
                    "lavender",
                    "lavenderblush",
                    "lawngreen",
                    "lemonchiffon",
                    "limegreen",
                    "linen",
                    "magenta",
                    "maroon",
                    "midnightblue",
                    "mintcream",
                    "mistyrose",
                    "moccasin",
                    "navajowhite",
                    "navy",
                    "navyblue",
                    "oldlace",
                    "olivedrab",
                    "orange",
                    "orangered",
                    "orchid",
                    "palegoldenrod",
                    "palegreen",
                    "paleturquoise",
                    "palevioletred",
                    "papayawhip",
                    "peachpuff",
                    "peru",
                    "pink",
                    "plum",
                    "powderblue",
                    "purple",
                    "red",
                    "rosybrown",
                    "royalblue",
                    "saddlebrown",
                    "salmon",
                    "sandybrown",
                    "seagreen",
                    "seashell",
                    "sienna",
                    "skyblue",
                    "slateblue",
                    "slategray",
                    "slategrey",
                    "snow",
                    "springgreen",
                    "steelblue",
                    "tan",
                    "thistle",
                    "tomato",
                    "turquoise",
                    "violet",
                    "violetred",
                    "wheat",
                    "whitesmoke",
                    "yellow",
                    "yellowgreen"))
            private$..size_interval <- jmvcore::OptionList$new(
                "size_interval",
                size_interval,
                default="1",
                options=list(
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6"))
            private$..alpha_interval <- jmvcore::OptionList$new(
                "alpha_interval",
                alpha_interval,
                default="1",
                options=list(
                    "1",
                    ".75",
                    ".5",
                    ".25",
                    "0"))
            private$..alpha_error <- jmvcore::OptionList$new(
                "alpha_error",
                alpha_error,
                default="1",
                options=list(
                    "1",
                    ".75",
                    ".5",
                    ".25",
                    "0"))
            private$..fill_error <- jmvcore::OptionList$new(
                "fill_error",
                fill_error,
                default="gray",
                options=list(
                    "white",
                    "aliceblue",
                    "antiquewhite",
                    "aquamarine",
                    "azure",
                    "beige",
                    "bisque",
                    "black",
                    "blanchedalmond",
                    "blue",
                    "blueviolet",
                    "brown",
                    "burlywood",
                    "cadetblue",
                    "chartreuse",
                    "chocolate",
                    "coral",
                    "cornflowerblue",
                    "cornsilk",
                    "cyan",
                    "deeppink",
                    "deepskyblue",
                    "dimgray",
                    "dimgrey",
                    "dodgerblue",
                    "firebrick",
                    "floralwhite",
                    "forestgreen",
                    "gainsboro",
                    "ghostwhite",
                    "gold",
                    "goldenrod",
                    "gray",
                    "green",
                    "greenyellow",
                    "grey",
                    "honeydew",
                    "hotpink",
                    "indianred",
                    "ivory",
                    "khaki",
                    "lavender",
                    "lavenderblush",
                    "lawngreen",
                    "lemonchiffon",
                    "limegreen",
                    "linen",
                    "magenta",
                    "maroon",
                    "midnightblue",
                    "mintcream",
                    "mistyrose",
                    "moccasin",
                    "navajowhite",
                    "navy",
                    "navyblue",
                    "oldlace",
                    "olivedrab",
                    "orange",
                    "orangered",
                    "orchid",
                    "palegoldenrod",
                    "palegreen",
                    "paleturquoise",
                    "palevioletred",
                    "papayawhip",
                    "peachpuff",
                    "peru",
                    "pink",
                    "plum",
                    "powderblue",
                    "purple",
                    "red",
                    "rosybrown",
                    "royalblue",
                    "saddlebrown",
                    "salmon",
                    "sandybrown",
                    "seagreen",
                    "seashell",
                    "sienna",
                    "skyblue",
                    "slateblue",
                    "slategray",
                    "slategrey",
                    "snow",
                    "springgreen",
                    "steelblue",
                    "tan",
                    "thistle",
                    "tomato",
                    "turquoise",
                    "violet",
                    "violetred",
                    "wheat",
                    "whitesmoke",
                    "yellow",
                    "yellowgreen"))

            self$.addOption(private$..switch)
            self$.addOption(private$..outcome_variable)
            self$.addOption(private$..mean)
            self$.addOption(private$..sd)
            self$.addOption(private$..n)
            self$.addOption(private$..outcome_variable_name)
            self$.addOption(private$..conf_level)
            self$.addOption(private$..show_details)
            self$.addOption(private$..es_plot_width)
            self$.addOption(private$..es_plot_height)
            self$.addOption(private$..ymin)
            self$.addOption(private$..ymax)
            self$.addOption(private$..breaks)
            self$.addOption(private$..ylab)
            self$.addOption(private$..xlab)
            self$.addOption(private$..axis.text.y)
            self$.addOption(private$..axis.title.y)
            self$.addOption(private$..axis.text.x)
            self$.addOption(private$..axis.title.x)
            self$.addOption(private$..error_layout)
            self$.addOption(private$..error_scale)
            self$.addOption(private$..error_nudge)
            self$.addOption(private$..data_layout)
            self$.addOption(private$..data_spread)
            self$.addOption(private$..shape_raw)
            self$.addOption(private$..shape_summary)
            self$.addOption(private$..color_raw)
            self$.addOption(private$..color_summary)
            self$.addOption(private$..fill_raw)
            self$.addOption(private$..fill_summary)
            self$.addOption(private$..size_raw)
            self$.addOption(private$..size_summary)
            self$.addOption(private$..alpha_raw)
            self$.addOption(private$..alpha_summary)
            self$.addOption(private$..linetype_summary)
            self$.addOption(private$..color_interval)
            self$.addOption(private$..size_interval)
            self$.addOption(private$..alpha_interval)
            self$.addOption(private$..alpha_error)
            self$.addOption(private$..fill_error)
        }),
    active = list(
        switch = function() private$..switch$value,
        outcome_variable = function() private$..outcome_variable$value,
        mean = function() private$..mean$value,
        sd = function() private$..sd$value,
        n = function() private$..n$value,
        outcome_variable_name = function() private$..outcome_variable_name$value,
        conf_level = function() private$..conf_level$value,
        show_details = function() private$..show_details$value,
        es_plot_width = function() private$..es_plot_width$value,
        es_plot_height = function() private$..es_plot_height$value,
        ymin = function() private$..ymin$value,
        ymax = function() private$..ymax$value,
        breaks = function() private$..breaks$value,
        ylab = function() private$..ylab$value,
        xlab = function() private$..xlab$value,
        axis.text.y = function() private$..axis.text.y$value,
        axis.title.y = function() private$..axis.title.y$value,
        axis.text.x = function() private$..axis.text.x$value,
        axis.title.x = function() private$..axis.title.x$value,
        error_layout = function() private$..error_layout$value,
        error_scale = function() private$..error_scale$value,
        error_nudge = function() private$..error_nudge$value,
        data_layout = function() private$..data_layout$value,
        data_spread = function() private$..data_spread$value,
        shape_raw = function() private$..shape_raw$value,
        shape_summary = function() private$..shape_summary$value,
        color_raw = function() private$..color_raw$value,
        color_summary = function() private$..color_summary$value,
        fill_raw = function() private$..fill_raw$value,
        fill_summary = function() private$..fill_summary$value,
        size_raw = function() private$..size_raw$value,
        size_summary = function() private$..size_summary$value,
        alpha_raw = function() private$..alpha_raw$value,
        alpha_summary = function() private$..alpha_summary$value,
        linetype_summary = function() private$..linetype_summary$value,
        color_interval = function() private$..color_interval$value,
        size_interval = function() private$..size_interval$value,
        alpha_interval = function() private$..alpha_interval$value,
        alpha_error = function() private$..alpha_error$value,
        fill_error = function() private$..fill_error$value),
    private = list(
        ..switch = NA,
        ..outcome_variable = NA,
        ..mean = NA,
        ..sd = NA,
        ..n = NA,
        ..outcome_variable_name = NA,
        ..conf_level = NA,
        ..show_details = NA,
        ..es_plot_width = NA,
        ..es_plot_height = NA,
        ..ymin = NA,
        ..ymax = NA,
        ..breaks = NA,
        ..ylab = NA,
        ..xlab = NA,
        ..axis.text.y = NA,
        ..axis.title.y = NA,
        ..axis.text.x = NA,
        ..axis.title.x = NA,
        ..error_layout = NA,
        ..error_scale = NA,
        ..error_nudge = NA,
        ..data_layout = NA,
        ..data_spread = NA,
        ..shape_raw = NA,
        ..shape_summary = NA,
        ..color_raw = NA,
        ..color_summary = NA,
        ..fill_raw = NA,
        ..fill_summary = NA,
        ..size_raw = NA,
        ..size_summary = NA,
        ..alpha_raw = NA,
        ..alpha_summary = NA,
        ..linetype_summary = NA,
        ..color_interval = NA,
        ..size_interval = NA,
        ..alpha_interval = NA,
        ..alpha_error = NA,
        ..fill_error = NA)
)

jamovimagnitudeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovimagnitudeResults",
    inherit = jmvcore::Group,
    active = list(
        debug = function() private$.items[["debug"]],
        help = function() private$.items[["help"]],
        overview = function() private$.items[["overview"]],
        magnitude_plot_warnings = function() private$.items[["magnitude_plot_warnings"]],
        magnitude_plot = function() private$.items[["magnitude_plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Estimate Magnitude")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="debug",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="help",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="overview",
                title="Overview",
                rows="(outcome_variable)",
                columns=list(
                    list(
                        `name`="outcome_variable_name", 
                        `title`="Outcome variable", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="mean", 
                        `type`="number", 
                        `title`="<i>M</i>"),
                    list(
                        `name`="mean_LL", 
                        `title`="LL", 
                        `type`="number", 
                        `visible`="(effect_size == 'mean_difference')"),
                    list(
                        `name`="mean_UL", 
                        `title`="UL", 
                        `type`="number", 
                        `visible`="(effect_size == 'mean_difference')"),
                    list(
                        `name`="median", 
                        `title`="Mdn", 
                        `type`="number", 
                        `visible`="(switch == 'from_raw')"),
                    list(
                        `name`="median_LL", 
                        `title`="LL", 
                        `type`="number", 
                        `visible`="(effect_size == 'median_difference' & switch == 'from_raw')"),
                    list(
                        `name`="median_UL", 
                        `title`="UL", 
                        `type`="number", 
                        `visible`="(effect_size == 'median_difference' & switch == 'from_raw')"),
                    list(
                        `name`="sd", 
                        `type`="number", 
                        `title`="<i>s</i>"),
                    list(
                        `name`="min", 
                        `title`="Minimum", 
                        `type`="number", 
                        `visible`="(switch == 'from_raw')"),
                    list(
                        `name`="max", 
                        `title`="Maximum", 
                        `type`="number", 
                        `visible`="(switch == 'from_raw')"),
                    list(
                        `name`="q1", 
                        `title`="25th", 
                        `type`="number", 
                        `superTitle`="Percentile", 
                        `visible`="(switch == 'from_raw')"),
                    list(
                        `name`="q3", 
                        `title`="75th", 
                        `type`="number", 
                        `superTitle`="Percentile", 
                        `visible`="(switch == 'from_raw')"),
                    list(
                        `name`="n", 
                        `title`="<i>n</i>", 
                        `type`="integer"),
                    list(
                        `name`="missing", 
                        `type`="integer", 
                        `title`="Missing", 
                        `visible`="(switch == 'from_raw')"),
                    list(
                        `name`="df", 
                        `title`="<i>df</i>", 
                        `type`="integer", 
                        `visible`="(show_details)"),
                    list(
                        `name`="mean_SE", 
                        `title`="<i>SEM</i>", 
                        `type`="number", 
                        `visible`="(show_details)"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="magnitude_plot_warnings",
                title="Figure warnings",
                visible=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="magnitude_plot",
                title="Magnitude",
                requiresData=TRUE,
                width=400,
                height=300,
                renderFun=".magnitude_plot"))}))

jamovimagnitudeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovimagnitudeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "esci4",
                name = "jamovimagnitude",
                version = c(1,0,0),
                options = options,
                results = jamovimagnitudeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Estimate Magnitude
#'
#' 
#' @param switch .
#' @param data .
#' @param outcome_variable .
#' @param mean .
#' @param sd .
#' @param n .
#' @param outcome_variable_name .
#' @param conf_level .
#' @param show_details .
#' @param es_plot_width .
#' @param es_plot_height .
#' @param ymin .
#' @param ymax .
#' @param breaks .
#' @param ylab .
#' @param xlab .
#' @param axis.text.y .
#' @param axis.title.y .
#' @param axis.text.x .
#' @param axis.title.x .
#' @param error_layout .
#' @param error_scale .
#' @param error_nudge .
#' @param data_layout .
#' @param data_spread .
#' @param shape_raw .
#' @param shape_summary .
#' @param color_raw .
#' @param color_summary .
#' @param fill_raw .
#' @param fill_summary .
#' @param size_raw .
#' @param size_summary .
#' @param alpha_raw .
#' @param alpha_summary .
#' @param linetype_summary .
#' @param color_interval .
#' @param size_interval .
#' @param alpha_interval .
#' @param alpha_error .
#' @param fill_error .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$debug} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$help} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$overview} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$magnitude_plot_warnings} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$magnitude_plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$overview$asDF}
#'
#' \code{as.data.frame(results$overview)}
#'
#' @export
jamovimagnitude <- function(
    switch = "from_raw",
    data,
    outcome_variable,
    mean = "",
    sd = "",
    n = "",
    outcome_variable_name = "Outcome variable",
    conf_level = 95,
    show_details = FALSE,
    es_plot_width = "450",
    es_plot_height = "450",
    ymin = "auto",
    ymax = "auto",
    breaks = "auto",
    ylab = "auto",
    xlab = "auto",
    axis.text.y = "10",
    axis.title.y = "12",
    axis.text.x = "10",
    axis.title.x = "12",
    error_layout = "halfeye",
    error_scale = "0.25",
    error_nudge = "0.4",
    data_layout = "random",
    data_spread = "0.25",
    shape_raw = "circle filled",
    shape_summary = "circle filled",
    color_raw = "gray",
    color_summary = "black",
    fill_raw = "white",
    fill_summary = "black",
    size_raw = "2",
    size_summary = "3",
    alpha_raw = "1",
    alpha_summary = "1",
    linetype_summary = "solid",
    color_interval = "black",
    size_interval = "1",
    alpha_interval = "1",
    alpha_error = "1",
    fill_error = "gray") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jamovimagnitude requires jmvcore to be installed (restart may be required)")

    if ( ! missing(outcome_variable)) outcome_variable <- jmvcore::resolveQuo(jmvcore::enquo(outcome_variable))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(outcome_variable), outcome_variable, NULL))


    options <- jamovimagnitudeOptions$new(
        switch = switch,
        outcome_variable = outcome_variable,
        mean = mean,
        sd = sd,
        n = n,
        outcome_variable_name = outcome_variable_name,
        conf_level = conf_level,
        show_details = show_details,
        es_plot_width = es_plot_width,
        es_plot_height = es_plot_height,
        ymin = ymin,
        ymax = ymax,
        breaks = breaks,
        ylab = ylab,
        xlab = xlab,
        axis.text.y = axis.text.y,
        axis.title.y = axis.title.y,
        axis.text.x = axis.text.x,
        axis.title.x = axis.title.x,
        error_layout = error_layout,
        error_scale = error_scale,
        error_nudge = error_nudge,
        data_layout = data_layout,
        data_spread = data_spread,
        shape_raw = shape_raw,
        shape_summary = shape_summary,
        color_raw = color_raw,
        color_summary = color_summary,
        fill_raw = fill_raw,
        fill_summary = fill_summary,
        size_raw = size_raw,
        size_summary = size_summary,
        alpha_raw = alpha_raw,
        alpha_summary = alpha_summary,
        linetype_summary = linetype_summary,
        color_interval = color_interval,
        size_interval = size_interval,
        alpha_interval = alpha_interval,
        alpha_error = alpha_error,
        fill_error = fill_error)

    analysis <- jamovimagnitudeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

