
# This file is automatically generated, you probably don't want to edit this

jamovipdiffindcontrastOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovipdiffindcontrastOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            outcome_variable = NULL,
            grouping_variable = NULL,
            means = NULL,
            sds = NULL,
            ns = NULL,
            grouping_variable_labels = NULL,
            outcome_variable_name = "Outcome variable",
            grouping_variable_name = "Grouping variable",
            comparison_levels = NULL,
            reference_levels = NULL,
            conf_level = 95,
            assume_equal_variance = TRUE, ...) {

            super$initialize(
                package="esci4",
                name="jamovipdiffindcontrast",
                requiresData=TRUE,
                ...)

            private$..outcome_variable <- jmvcore::OptionVariable$new(
                "outcome_variable",
                outcome_variable,
                permitted=list(
                    "numeric"))
            private$..grouping_variable <- jmvcore::OptionVariable$new(
                "grouping_variable",
                grouping_variable,
                permitted=list(
                    "factor"))
            private$..means <- jmvcore::OptionVariable$new(
                "means",
                means,
                permitted=list(
                    "numeric"))
            private$..sds <- jmvcore::OptionVariable$new(
                "sds",
                sds,
                permitted=list(
                    "numeric"))
            private$..ns <- jmvcore::OptionVariable$new(
                "ns",
                ns,
                permitted=list(
                    "numeric"))
            private$..grouping_variable_labels <- jmvcore::OptionVariable$new(
                "grouping_variable_labels",
                grouping_variable_labels,
                permitted=list(
                    "factor"))
            private$..outcome_variable_name <- jmvcore::OptionString$new(
                "outcome_variable_name",
                outcome_variable_name,
                default="Outcome variable")
            private$..grouping_variable_name <- jmvcore::OptionString$new(
                "grouping_variable_name",
                grouping_variable_name,
                default="Grouping variable")
            private$..comparison_levels <- jmvcore::OptionString$new(
                "comparison_levels",
                comparison_levels)
            private$..reference_levels <- jmvcore::OptionString$new(
                "reference_levels",
                reference_levels)
            private$..conf_level <- jmvcore::OptionNumber$new(
                "conf_level",
                conf_level,
                min=1,
                max=99.999999,
                default=95)
            private$..assume_equal_variance <- jmvcore::OptionBool$new(
                "assume_equal_variance",
                assume_equal_variance,
                default=TRUE)

            self$.addOption(private$..outcome_variable)
            self$.addOption(private$..grouping_variable)
            self$.addOption(private$..means)
            self$.addOption(private$..sds)
            self$.addOption(private$..ns)
            self$.addOption(private$..grouping_variable_labels)
            self$.addOption(private$..outcome_variable_name)
            self$.addOption(private$..grouping_variable_name)
            self$.addOption(private$..comparison_levels)
            self$.addOption(private$..reference_levels)
            self$.addOption(private$..conf_level)
            self$.addOption(private$..assume_equal_variance)
        }),
    active = list(
        outcome_variable = function() private$..outcome_variable$value,
        grouping_variable = function() private$..grouping_variable$value,
        means = function() private$..means$value,
        sds = function() private$..sds$value,
        ns = function() private$..ns$value,
        grouping_variable_labels = function() private$..grouping_variable_labels$value,
        outcome_variable_name = function() private$..outcome_variable_name$value,
        grouping_variable_name = function() private$..grouping_variable_name$value,
        comparison_levels = function() private$..comparison_levels$value,
        reference_levels = function() private$..reference_levels$value,
        conf_level = function() private$..conf_level$value,
        assume_equal_variance = function() private$..assume_equal_variance$value),
    private = list(
        ..outcome_variable = NA,
        ..grouping_variable = NA,
        ..means = NA,
        ..sds = NA,
        ..ns = NA,
        ..grouping_variable_labels = NA,
        ..outcome_variable_name = NA,
        ..grouping_variable_name = NA,
        ..comparison_levels = NA,
        ..reference_levels = NA,
        ..conf_level = NA,
        ..assume_equal_variance = NA)
)

jamovipdiffindcontrastResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovipdiffindcontrastResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Proportions: Independent Groups Contrast")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Proportion Difference - Independent Groups Contrast"))}))

jamovipdiffindcontrastBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovipdiffindcontrastBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "esci4",
                name = "jamovipdiffindcontrast",
                version = c(1,0,0),
                options = options,
                results = jamovipdiffindcontrastResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Independent Groups Contrast
#'
#' 
#' @param data .
#' @param outcome_variable .
#' @param grouping_variable .
#' @param means .
#' @param sds .
#' @param ns .
#' @param grouping_variable_labels .
#' @param outcome_variable_name .
#' @param grouping_variable_name .
#' @param comparison_levels .
#' @param reference_levels .
#' @param conf_level .
#' @param assume_equal_variance .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
jamovipdiffindcontrast <- function(
    data,
    outcome_variable,
    grouping_variable,
    means,
    sds,
    ns,
    grouping_variable_labels,
    outcome_variable_name = "Outcome variable",
    grouping_variable_name = "Grouping variable",
    comparison_levels,
    reference_levels,
    conf_level = 95,
    assume_equal_variance = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jamovipdiffindcontrast requires jmvcore to be installed (restart may be required)")

    if ( ! missing(outcome_variable)) outcome_variable <- jmvcore::resolveQuo(jmvcore::enquo(outcome_variable))
    if ( ! missing(grouping_variable)) grouping_variable <- jmvcore::resolveQuo(jmvcore::enquo(grouping_variable))
    if ( ! missing(means)) means <- jmvcore::resolveQuo(jmvcore::enquo(means))
    if ( ! missing(sds)) sds <- jmvcore::resolveQuo(jmvcore::enquo(sds))
    if ( ! missing(ns)) ns <- jmvcore::resolveQuo(jmvcore::enquo(ns))
    if ( ! missing(grouping_variable_labels)) grouping_variable_labels <- jmvcore::resolveQuo(jmvcore::enquo(grouping_variable_labels))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(outcome_variable), outcome_variable, NULL),
            `if`( ! missing(grouping_variable), grouping_variable, NULL),
            `if`( ! missing(means), means, NULL),
            `if`( ! missing(sds), sds, NULL),
            `if`( ! missing(ns), ns, NULL),
            `if`( ! missing(grouping_variable_labels), grouping_variable_labels, NULL))

    for (v in grouping_variable) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in grouping_variable_labels) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- jamovipdiffindcontrastOptions$new(
        outcome_variable = outcome_variable,
        grouping_variable = grouping_variable,
        means = means,
        sds = sds,
        ns = ns,
        grouping_variable_labels = grouping_variable_labels,
        outcome_variable_name = outcome_variable_name,
        grouping_variable_name = grouping_variable_name,
        comparison_levels = comparison_levels,
        reference_levels = reference_levels,
        conf_level = conf_level,
        assume_equal_variance = assume_equal_variance)

    analysis <- jamovipdiffindcontrastClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

