
# This file is automatically generated, you probably don't want to edit this

jamovimdiffpairedOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovimdiffpairedOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            switch = "from_raw",
            comparison_measure = NULL,
            reference_variable = NULL,
            comparison_mean = NULL,
            comparison_sd = NULL,
            reference_mean = NULL,
            reference_sd = NULL,
            n = NULL,
            r = NULL,
            comparison_measure_name = "Comparison measure",
            reference_measure_name = "Reference measure",
            conf_level = 95, ...) {

            super$initialize(
                package="esci4",
                name="jamovimdiffpaired",
                requiresData=TRUE,
                ...)

            private$..switch <- jmvcore::OptionList$new(
                "switch",
                switch,
                default="from_raw",
                options=list(
                    "from_raw",
                    "from_summary"))
            private$..comparison_measure <- jmvcore::OptionVariable$new(
                "comparison_measure",
                comparison_measure,
                permitted=list(
                    "numeric"))
            private$..reference_variable <- jmvcore::OptionVariable$new(
                "reference_variable",
                reference_variable,
                permitted=list(
                    "numeric"))
            private$..comparison_mean <- jmvcore::OptionNumber$new(
                "comparison_mean",
                comparison_mean)
            private$..comparison_sd <- jmvcore::OptionNumber$new(
                "comparison_sd",
                comparison_sd)
            private$..reference_mean <- jmvcore::OptionNumber$new(
                "reference_mean",
                reference_mean)
            private$..reference_sd <- jmvcore::OptionNumber$new(
                "reference_sd",
                reference_sd)
            private$..n <- jmvcore::OptionInteger$new(
                "n",
                n,
                min=1)
            private$..r <- jmvcore::OptionNumber$new(
                "r",
                r,
                min=-1,
                max=1)
            private$..comparison_measure_name <- jmvcore::OptionString$new(
                "comparison_measure_name",
                comparison_measure_name,
                default="Comparison measure")
            private$..reference_measure_name <- jmvcore::OptionString$new(
                "reference_measure_name",
                reference_measure_name,
                default="Reference measure")
            private$..conf_level <- jmvcore::OptionNumber$new(
                "conf_level",
                conf_level,
                min=1,
                max=99.999999,
                default=95)

            self$.addOption(private$..switch)
            self$.addOption(private$..comparison_measure)
            self$.addOption(private$..reference_variable)
            self$.addOption(private$..comparison_mean)
            self$.addOption(private$..comparison_sd)
            self$.addOption(private$..reference_mean)
            self$.addOption(private$..reference_sd)
            self$.addOption(private$..n)
            self$.addOption(private$..r)
            self$.addOption(private$..comparison_measure_name)
            self$.addOption(private$..reference_measure_name)
            self$.addOption(private$..conf_level)
        }),
    active = list(
        switch = function() private$..switch$value,
        comparison_measure = function() private$..comparison_measure$value,
        reference_variable = function() private$..reference_variable$value,
        comparison_mean = function() private$..comparison_mean$value,
        comparison_sd = function() private$..comparison_sd$value,
        reference_mean = function() private$..reference_mean$value,
        reference_sd = function() private$..reference_sd$value,
        n = function() private$..n$value,
        r = function() private$..r$value,
        comparison_measure_name = function() private$..comparison_measure_name$value,
        reference_measure_name = function() private$..reference_measure_name$value,
        conf_level = function() private$..conf_level$value),
    private = list(
        ..switch = NA,
        ..comparison_measure = NA,
        ..reference_variable = NA,
        ..comparison_mean = NA,
        ..comparison_sd = NA,
        ..reference_mean = NA,
        ..reference_sd = NA,
        ..n = NA,
        ..r = NA,
        ..comparison_measure_name = NA,
        ..reference_measure_name = NA,
        ..conf_level = NA)
)

jamovimdiffpairedResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovimdiffpairedResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Mdiff - Paired")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Mdiff - Paired"))}))

jamovimdiffpairedBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovimdiffpairedBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "esci4",
                name = "jamovimdiffpaired",
                version = c(1,0,0),
                options = options,
                results = jamovimdiffpairedResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Mdiff - Paired
#'
#' 
#' @param switch .
#' @param data .
#' @param comparison_measure .
#' @param reference_variable .
#' @param comparison_mean .
#' @param comparison_sd .
#' @param reference_mean .
#' @param reference_sd .
#' @param n .
#' @param r .
#' @param comparison_measure_name .
#' @param reference_measure_name .
#' @param conf_level .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
jamovimdiffpaired <- function(
    switch = "from_raw",
    data,
    comparison_measure,
    reference_variable,
    comparison_mean,
    comparison_sd,
    reference_mean,
    reference_sd,
    n,
    r,
    comparison_measure_name = "Comparison measure",
    reference_measure_name = "Reference measure",
    conf_level = 95) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jamovimdiffpaired requires jmvcore to be installed (restart may be required)")

    if ( ! missing(comparison_measure)) comparison_measure <- jmvcore::resolveQuo(jmvcore::enquo(comparison_measure))
    if ( ! missing(reference_variable)) reference_variable <- jmvcore::resolveQuo(jmvcore::enquo(reference_variable))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(comparison_measure), comparison_measure, NULL),
            `if`( ! missing(reference_variable), reference_variable, NULL))


    options <- jamovimdiffpairedOptions$new(
        switch = switch,
        comparison_measure = comparison_measure,
        reference_variable = reference_variable,
        comparison_mean = comparison_mean,
        comparison_sd = comparison_sd,
        reference_mean = reference_mean,
        reference_sd = reference_sd,
        n = n,
        r = r,
        comparison_measure_name = comparison_measure_name,
        reference_measure_name = reference_measure_name,
        conf_level = conf_level)

    analysis <- jamovimdiffpairedClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

